import React, { createContext, useContext, useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { extraTranslations } from "@/lib/i18nExtra";
import { hobbyUITranslations } from "@/lib/i18nHobbyUI";
import { missingTranslations } from "@/lib/i18nMissing";
import { voiceTranslations } from "@/lib/i18nVoice";
import { workoutTypeTranslations } from "@/lib/i18nWorkoutTypes";
import { jaExerciseIdentity } from "@/lib/i18nJaIdentity";

export const LANGS = [
  { code: "ja", label: "日本語", flag: "🇯🇵" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
  { code: "tr", label: "Türkçe", flag: "🇹🇷" },
  { code: "ko", label: "한국어", flag: "🇰🇷" },
  { code: "zh", label: "中文（简体）", flag: "🇨🇳" },
  { code: "zh-TW", label: "中文（繁體）", flag: "🇹🇼" },
  { code: "id", label: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "th", label: "ไทย", flag: "🇹🇭" },
  { code: "vi", label: "Tiếng Việt", flag: "🇻🇳" }
];

// Detect device language from browser settings
function detectDeviceLanguage() {
  const navLangs = navigator.languages || [navigator.language || ""];
  const supported = new Set(LANGS.map(l => l.code));
  for (const l of navLangs) {
    const lower = (l || "").toLowerCase();
    if (lower.includes("zh-tw") || lower.includes("zh-hant") || lower.includes("zh-hk") || lower.includes("zh-mo")) return "zh-TW";
    const base = lower.split("-")[0];
    if (supported.has(base)) return base;
    if (base === "zh") return "zh";
  }
  return "en";
}

const translations = {
  ja: {
    "nav.home": "ホーム", "nav.users": "仲間", "nav.messages": "メッセージ", "nav.timeline": "タイムライン", "nav.settings": "設定", "nav.goLive": "トレ開始",
    "common.back": "戻る", "common.save": "保存", "common.edit": "編集", "common.delete": "削除", "common.cancel": "キャンセル", "common.search": "検索", "common.loading": "読み込み中…", "common.online": "オンライン", "common.offline": "オフライン", "common.send": "送信", "common.follow": "フォロー", "common.following": "フォロー中", "common.message": "メッセージ", "common.block": "ブロック", "common.unblock": "ブロック解除", "common.mute": "ミュート", "common.unmute": "ミュート解除", "common.report": "通報", "common.logout": "ログアウト", "common.all": "すべて", "common.nearby": "近く", "common.trainingNow": "トレーニング中", "common.country": "国", "common.hobbies": "趣味", "common.purpose": "トレーニング目的", "common.bio": "自己紹介", "common.displayName": "ユーザー名", "common.selectCountry": "国を選択",
    "profile.followers": "フォロワー", "profile.following": "フォロー中", "profile.posts": "投稿一覧", "profile.noPosts": "まだ投稿がありません", "profile.notFound": "ユーザーが見つかりません", "profile.editTitle": "プロフィール編集", "profile.editAvatar": "画像を変更", "profile.noAvatar": "なし", "profile.hobbiesMax": "趣味（最大5つ）", "profile.purposePlaceholder": "選択してください",
    "users.title": "仲間を探す", "users.filterAll": "すべて", "users.filterNearby": "近く", "users.filterTraining": "トレ中", "users.filterCountry": "国", "users.filterHobby": "趣味", "users.filterPurpose": "目的", "users.noUsers": "ユーザーが見つかりません", "users.searchPlaceholder": "ユーザーを検索",
    "settings.title": "設定", "settings.editProfile": "プロフィール編集", "settings.editHobbies": "趣味を編集", "settings.editPurpose": "トレーニング目的を編集", "settings.notifications": "通知設定", "settings.language": "言語", "settings.darkMode": "ダークモード（今後対応）", "settings.logout": "ログアウト", "settings.account": "アカウント", "settings.preferences": "設定", "settings.shareLocation": "位置情報を地図に公開", "settings.shareLocationDesc": "オンにすると、地図上にプロフィールアイコンが表示されます。最大ズームでも2〜3km範囲までしか拡大できません。",
    "messages.title": "メッセージ", "messages.all": "すべて", "messages.requests": "リクエスト", "messages.empty": "メッセージはありません。プロフィールからDMを始めよう！", "messages.emptyRequests": "リクエストはありません", "messages.request": "メッセージリクエスト", "messages.requestDesc": "さんからのメッセージです。承認するとチャットを始められます。", "messages.accept": "承認", "messages.decline": "削除", "messages.awaiting": "相手の承認待ちです", "messages.blocked": "このユーザーをブロックしているため、メッセージを送れません。", "messages.inputPlaceholder": "メッセージを入力…", "messages.cantSend": "メッセージを送れません", "messages.acceptToStart": "承認してチャットを始めよう", "messages.awaitingShort": "承認待ち",
    "notifications.title": "通知", "notifications.empty": "通知はありません",
    "home.heroTitle": "トレーニングを始めよう", "home.heroSub": "ライブ配信で仲間と繋がり、位置情報を共有し、ランキング対決で本気を出す。", "home.record": "トレーニング記録", "home.viewLive": "ライブを見る", "home.liveNow": "いまトレーニング中", "home.trainingNow": "TRAINING NOW", "home.noLive": "いまトレーニング中の仲間はいません。最初にトレーニングを始めよう！", "home.leaderboard": "トップランカー", "home.recent": "みんなの記録", "home.totalVolume": "総ボリューム", "home.weekRecords": "今週の記録", "home.participants": "参加者", "home.liveCount": "配信中", "home.globe": "ワールドグローブ", "home.globeSub": "世界中でいま筋トレしている仲間が光る。位置は近隣にぼかして表示しています。", "home.trainingCount": "人 トレーニング中", "home.noLiveMap": "いまトレーニング中の仲間はいません", "home.popularPosts": "人気投稿", "home.noPosts": "まだ投稿がありません", "home.nearbyMap": "ローカルマップ", "home.nearbyMapSub": "地図で世界中の仲間を見つけよう。緑がオンライン、赤がいまトレーニング中。ピンをタップでプロフィールへ。", "home.you": "あなた", "home.nearbyUser": "近くのユーザー", "home.trainingLive": "トレーニング中", "home.nearbyCount": "人 近くにいます", "home.worldView": "🌍 世界表示", "home.locateMe": "現在地へ", "home.satellite": "航空写真", "home.normalMap": "地図", "home.filter_all": "すべて", "home.filter_online": "オンライン中", "home.filter_training": "トレーニング中", "home.filter_following": "フォロー中", "home.filter_nearby": "近くのユーザー", "home.online": "オンライン中", "home.offline": "オフライン",
    "auth.selectLanguage": "言語を選択",     "auth.welcome": "BELTVAへようこそ",
    "hobby_cat_sports": "スポーツ", "hobby_cat_games": "ゲーム", "hobby_cat_music": "音楽", "hobby_cat_anime": "映画・アニメ", "hobby_cat_travel": "旅行", "hobby_cat_reading": "読書", "hobby_cat_cafe": "カフェ", "hobby_cat_photo": "写真", "hobby_cat_cooking": "料理", "hobby_cat_fashion": "ファッション", "hobby_cat_car": "車", "hobby_cat_pet": "ペット",
    "purpose.hypertrophy": "筋肥大", "purpose.diet": "ダイエット", "purpose.health": "健康維持", "purpose.contest": "大会出場", "purpose.friends": "仲間募集"
  },
  en: {
    "nav.home": "Home", "nav.users": "Friends", "nav.messages": "Messages", "nav.timeline": "Timeline", "nav.settings": "Settings", "nav.goLive": "Start",
    "common.back": "Back", "common.save": "Save", "common.edit": "Edit", "common.delete": "Delete", "common.cancel": "Cancel", "common.search": "Search", "common.loading": "Loading…", "common.online": "Online", "common.offline": "Offline", "common.send": "Send", "common.follow": "Follow", "common.following": "Following", "common.message": "Message", "common.block": "Block", "common.unblock": "Unblock", "common.mute": "Mute", "common.unmute": "Unmute", "common.report": "Report", "common.logout": "Log out", "common.all": "All", "common.nearby": "Nearby", "common.trainingNow": "Training", "common.country": "Country", "common.hobbies": "Hobbies", "common.purpose": "Training goal", "common.bio": "Bio", "common.displayName": "Username", "common.selectCountry": "Select country",
    "profile.followers": "Followers", "profile.following": "Following", "profile.posts": "Posts", "profile.noPosts": "No posts yet", "profile.notFound": "User not found", "profile.editTitle": "Edit profile", "profile.editAvatar": "Change photo", "profile.noAvatar": "None", "profile.hobbiesMax": "Hobbies (up to 5)", "profile.purposePlaceholder": "Select",
    "users.title": "Find Friends", "users.filterAll": "All", "users.filterNearby": "Nearby", "users.filterTraining": "Training", "users.filterCountry": "Country", "users.filterHobby": "Hobby", "users.filterPurpose": "Goal", "users.noUsers": "No users found", "users.searchPlaceholder": "Search users",
    "settings.title": "Settings", "settings.editProfile": "Edit profile", "settings.editHobbies": "Edit hobbies", "settings.editPurpose": "Edit training goal", "settings.notifications": "Notifications", "settings.language": "Language", "settings.darkMode": "Dark mode (coming soon)", "settings.logout": "Log out", "settings.account": "Account", "settings.preferences": "Preferences", "settings.shareLocation": "Share location on map", "settings.shareLocationDesc": "When on, your profile icon appears on the map. Max zoom is limited to ~2–3 km range.",
    "messages.title": "Messages", "messages.all": "All", "messages.requests": "Requests", "messages.empty": "No messages. Start a DM from a profile!", "messages.emptyRequests": "No requests", "messages.request": "Message request", "messages.requestDesc": "sent you a message. Accept to start chatting.", "messages.accept": "Accept", "messages.decline": "Delete", "messages.awaiting": "Waiting for approval", "messages.blocked": "You blocked this user. You can't send messages.", "messages.inputPlaceholder": "Type a message…", "messages.cantSend": "Can't send messages", "messages.acceptToStart": "Accept to start chatting", "messages.awaitingShort": "Pending",
    "notifications.title": "Notifications", "notifications.empty": "No notifications",
    "home.heroTitle": "Let's train", "home.heroSub": "Connect live, share location, and compete on the leaderboard.", "home.record": "Log workout", "home.viewLive": "Watch live", "home.liveNow": "Training now", "home.trainingNow": "TRAINING NOW", "home.noLive": "No one training right now. Be the first!", "home.leaderboard": "Top rankers", "home.recent": "Recent records", "home.totalVolume": "Total volume", "home.weekRecords": "This week", "home.participants": "Participants", "home.liveCount": "Live", "home.globe": "World globe", "home.globeSub": "See who's training worldwide. Locations are blurred.", "home.trainingCount": "training now", "home.noLiveMap": "No one training right now", "home.popularPosts": "Popular posts", "home.noPosts": "No posts yet", "home.nearbyMap": "Local map", "home.nearbyMapSub": "Find training partners worldwide. Green = online, red = training now. Tap a pin to open their profile.", "home.you": "You", "home.nearbyUser": "Nearby user", "home.trainingLive": "Training now", "home.nearbyCount": "nearby", "home.worldView": "🌍 World", "home.locateMe": "Current location", "home.satellite": "Satellite", "home.normalMap": "Map", "home.filter_all": "All", "home.filter_online": "Online", "home.filter_training": "Training", "home.filter_following": "Following", "home.filter_nearby": "Nearby", "home.online": "Online", "home.offline": "Offline",
    "auth.selectLanguage": "Select language",     "auth.welcome": "Welcome to BELTVA",
    "hobby_cat_sports": "Sports", "hobby_cat_games": "Games", "hobby_cat_music": "Music", "hobby_cat_anime": "Anime & Film", "hobby_cat_travel": "Travel", "hobby_cat_reading": "Reading", "hobby_cat_cafe": "Cafe", "hobby_cat_photo": "Photo", "hobby_cat_cooking": "Cooking", "hobby_cat_fashion": "Fashion", "hobby_cat_car": "Car", "hobby_cat_pet": "Pet",
    "purpose.hypertrophy": "Hypertrophy", "purpose.diet": "Diet", "purpose.health": "Health", "purpose.contest": "Contest", "purpose.friends": "Find friends"
  },
  zh: {
    "nav.home": "首页", "nav.users": "伙伴", "nav.messages": "消息", "nav.timeline": "动态", "nav.settings": "设置", "nav.goLive": "开始",
    "common.back": "返回", "common.save": "保存", "common.edit": "编辑", "common.delete": "删除", "common.cancel": "取消", "common.search": "搜索", "common.loading": "加载中…", "common.online": "在线", "common.offline": "离线", "common.send": "发送", "common.follow": "关注", "common.following": "已关注", "common.message": "消息", "common.block": "拉黑", "common.unblock": "取消拉黑", "common.mute": "免打扰", "common.unmute": "取消免打扰", "common.report": "举报", "common.logout": "退出登录", "common.all": "全部", "common.nearby": "附近", "common.trainingNow": "训练中", "common.country": "国家", "common.hobbies": "兴趣", "common.purpose": "训练目标", "common.bio": "简介", "common.displayName": "用户名", "common.selectCountry": "选择国家",
    "profile.followers": "粉丝", "profile.following": "关注", "profile.posts": "帖子", "profile.noPosts": "暂无帖子", "profile.notFound": "未找到用户", "profile.editTitle": "编辑资料", "profile.editAvatar": "更换照片", "profile.noAvatar": "无", "profile.hobbiesMax": "兴趣（最多5个）", "profile.purposePlaceholder": "请选择",
    "users.title": "寻找伙伴", "users.filterAll": "全部", "users.filterNearby": "附近", "users.filterTraining": "训练中", "users.filterCountry": "国家", "users.filterHobby": "兴趣", "users.filterPurpose": "目标", "users.noUsers": "未找到用户", "users.searchPlaceholder": "搜索用户",
    "settings.title": "设置", "settings.editProfile": "编辑资料", "settings.editHobbies": "编辑兴趣", "settings.editPurpose": "编辑训练目标", "settings.notifications": "通知设置", "settings.language": "语言", "settings.darkMode": "深色模式（即将推出）", "settings.logout": "退出登录", "settings.account": "账号", "settings.preferences": "偏好",
    "messages.title": "消息", "messages.all": "全部", "messages.requests": "请求", "messages.empty": "没有消息。去资料页发起私信吧！", "messages.emptyRequests": "没有请求", "messages.request": "消息请求", "messages.requestDesc": "给你发了消息。通过后即可开始聊天。", "messages.accept": "通过", "messages.decline": "删除", "messages.awaiting": "等待对方通过", "messages.blocked": "你已拉黑该用户，无法发送消息。", "messages.inputPlaceholder": "输入消息…", "messages.cantSend": "无法发送消息", "messages.acceptToStart": "通过后开始聊天", "messages.awaitingShort": "待通过",
    "notifications.title": "通知", "notifications.empty": "暂无通知",
    "home.heroTitle": "开始训练吧", "home.heroSub": "直播连线、共享位置、排行榜对决。", "home.record": "记录训练", "home.viewLive": "看直播", "home.liveNow": "正在训练", "home.trainingNow": "TRAINING NOW", "home.noLive": "当前没人训练。成为第一个吧！", "home.leaderboard": "排行榜", "home.recent": "最新记录", "home.totalVolume": "总训练量", "home.weekRecords": "本周记录", "home.participants": "参与者", "home.liveCount": "直播中", "home.globe": "世界地球", "home.globeSub": "看看世界各地正在训练的伙伴。位置已模糊。", "home.trainingCount": "人正在训练", "home.noLiveMap": "当前没人训练", "home.popularPosts": "热门帖子", "home.noPosts": "暂无帖子", "home.nearbyMap": "本地地图", "home.nearbyMapSub": "在全球地图上找到训练伙伴。绿色=在线，红色=正在训练。点击图钉查看资料。", "home.you": "你", "home.nearbyUser": "附近用户", "home.trainingLive": "训练中", "home.nearbyCount": "人在附近", "home.worldView": "🌍 世界", "home.locateMe": "当前位置", "home.satellite": "卫星图", "home.normalMap": "地图", "home.filter_all": "全部", "home.filter_online": "在线", "home.filter_training": "训练中", "home.filter_following": "已关注", "home.filter_nearby": "附近用户", "home.online": "在线", "home.offline": "离线",
    "auth.selectLanguage": "选择语言",     "auth.welcome": "歡迎來到 BELTVA",
    "hobby_cat_sports": "运动", "hobby_cat_games": "游戏", "hobby_cat_music": "音乐", "hobby_cat_anime": "影视动漫", "hobby_cat_travel": "旅行", "hobby_cat_reading": "阅读", "hobby_cat_cafe": "咖啡", "hobby_cat_photo": "摄影", "hobby_cat_cooking": "烹饪", "hobby_cat_fashion": "时尚", "hobby_cat_car": "汽车", "hobby_cat_pet": "宠物",
    "purpose.hypertrophy": "增肌", "purpose.diet": "减脂", "purpose.health": "保持健康", "purpose.contest": "参加比赛", "purpose.friends": "找伙伴"
  },
  ko: {
    "nav.home": "홈", "nav.users": "친구", "nav.messages": "메시지", "nav.timeline": "타임라인", "nav.settings": "설정", "nav.goLive": "시작",
    "common.back": "뒤로", "common.save": "저장", "common.edit": "편집", "common.delete": "삭제", "common.cancel": "취소", "common.search": "검색", "common.loading": "로딩 중…", "common.online": "온라인", "common.offline": "오프라인", "common.send": "전송", "common.follow": "팔로우", "common.following": "팔로잉", "common.message": "메시지", "common.block": "차단", "common.unblock": "차단 해제", "common.mute": "알림 끄기", "common.unmute": "알림 켜기", "common.report": "신고", "common.logout": "로그아웃", "common.all": "전체", "common.nearby": "근처", "common.trainingNow": "운동 중", "common.country": "국가", "common.hobbies": "취미", "common.purpose": "운동 목표", "common.bio": "소개", "common.displayName": "유저명", "common.selectCountry": "국가 선택",
    "profile.followers": "팔로워", "profile.following": "팔로잉", "profile.posts": "게시물", "profile.noPosts": "게시물이 없습니다", "profile.notFound": "유저를 찾을 수 없습니다", "profile.editTitle": "프로필 편집", "profile.editAvatar": "사진 변경", "profile.noAvatar": "없음", "profile.hobbiesMax": "취미 (최대 5개)", "profile.purposePlaceholder": "선택",
    "users.title": "친구 찾기", "users.filterAll": "전체", "users.filterNearby": "근처", "users.filterTraining": "운동 중", "users.filterCountry": "국가", "users.filterHobby": "취미", "users.filterPurpose": "목표", "users.noUsers": "유저가 없습니다", "users.searchPlaceholder": "유저 검색",
    "settings.title": "설정", "settings.editProfile": "프로필 편집", "settings.editHobbies": "취미 편집", "settings.editPurpose": "운동 목표 편집", "settings.notifications": "알림 설정", "settings.language": "언어", "settings.darkMode": "다크 모드 (예정)", "settings.logout": "로그아웃", "settings.account": "계정", "settings.preferences": "환경설정",
    "messages.title": "메시지", "messages.all": "전체", "messages.requests": "요청", "messages.empty": "메시지가 없습니다. 프로필에서 DM을 시작하세요!", "messages.emptyRequests": "요청이 없습니다", "messages.request": "메시지 요청", "messages.requestDesc": "님이 메시지를 보냈습니다. 승인하면 채팅을 시작할 수 있습니다.", "messages.accept": "승인", "messages.decline": "삭제", "messages.awaiting": "상대 승인 대기 중", "messages.blocked": "이 유저를 차단하여 메시지를 보낼 수 없습니다.", "messages.inputPlaceholder": "메시지 입력…", "messages.cantSend": "메시지를 보낼 수 없습니다", "messages.acceptToStart": "승인하여 채팅 시작", "messages.awaitingShort": "대기 중",
    "notifications.title": "알림", "notifications.empty": "알림이 없습니다",
    "home.heroTitle": "운동을 시작해요", "home.heroSub": "라이브로 친구와 연결하고 위치를 공유하며 랭킹 대결.", "home.record": "운동 기록", "home.viewLive": "라이브 보기", "home.liveNow": "지금 운동 중", "home.trainingNow": "TRAINING NOW", "home.noLive": "지금 운동 중인 친구가 없습니다. 먼저 시작해 보세요!", "home.leaderboard": "탑 랭커", "home.recent": "최근 기록", "home.totalVolume": "총 볼륨", "home.weekRecords": "이번 주 기록", "home.participants": "참가자", "home.liveCount": "라이브", "home.globe": "월드 글로브", "home.globeSub": "전 세계에서 운동 중인 친구들이 빛납니다. 위치는 흐려져 표시됩니다.", "home.trainingCount": "명 운동 중", "home.noLiveMap": "지금 운동 중인 친구가 없습니다", "home.popularPosts": "인기 게시물", "home.noPosts": "게시물이 없습니다", "home.nearbyMap": "로컬 지도", "home.nearbyMapSub": "지도에서 전 세계 운동 친구를 찾아보세요. 초록=온라인, 빨강=운동 중. 핀을 탭하면 프로필로.", "home.you": "나", "home.nearbyUser": "근처 유저", "home.trainingLive": "운동 중", "home.nearbyCount": "명 근처에 있음", "home.worldView": "🌍 세계", "home.locateMe": "현재 위치", "home.satellite": "위성", "home.normalMap": "지도", "home.filter_all": "전체", "home.filter_online": "온라인", "home.filter_training": "운동 중", "home.filter_following": "팔로잉", "home.filter_nearby": "근처 유저", "home.online": "온라인", "home.offline": "오프라인",
    "auth.selectLanguage": "언어 선택",     "auth.welcome": "BELTVA에 오신 것을 환영합니다",
    "hobby_cat_sports": "스포츠", "hobby_cat_games": "게임", "hobby_cat_music": "음악", "hobby_cat_anime": "영화/애니", "hobby_cat_travel": "여행", "hobby_cat_reading": "독서", "hobby_cat_cafe": "카페", "hobby_cat_photo": "사진", "hobby_cat_cooking": "요리", "hobby_cat_fashion": "패션", "hobby_cat_car": "자동차", "hobby_cat_pet": "반려동물",
    "purpose.hypertrophy": "근비대", "purpose.diet": "다이어트", "purpose.health": "건강 유지", "purpose.contest": "대회 출전", "purpose.friends": "친구 모집"
  },
  es: {
    "nav.home": "Inicio", "nav.users": "Amigos", "nav.messages": "Mensajes", "nav.timeline": "Línea de tiempo", "nav.settings": "Ajustes", "nav.goLive": "Empezar",
    "common.back": "Atrás", "common.save": "Guardar", "common.edit": "Editar", "common.delete": "Eliminar", "common.cancel": "Cancelar", "common.search": "Buscar", "common.loading": "Cargando…", "common.online": "En línea", "common.offline": "Desconectado", "common.send": "Enviar", "common.follow": "Seguir", "common.following": "Siguiendo", "common.message": "Mensaje", "common.block": "Bloquear", "common.unblock": "Desbloquear", "common.mute": "Silenciar", "common.unmute": "Activar", "common.report": "Reportar", "common.logout": "Cerrar sesión", "common.all": "Todos", "common.nearby": "Cerca", "common.trainingNow": "Entrenando", "common.country": "País", "common.hobbies": "Aficiones", "common.purpose": "Objetivo", "common.bio": "Bio", "common.displayName": "Usuario", "common.selectCountry": "Selecciona país",
    "profile.followers": "Seguidores", "profile.following": "Siguiendo", "profile.posts": "Publicaciones", "profile.noPosts": "Aún no hay publicaciones", "profile.notFound": "Usuario no encontrado", "profile.editTitle": "Editar perfil", "profile.editAvatar": "Cambiar foto", "profile.noAvatar": "Sin foto", "profile.hobbiesMax": "Aficiones (máx. 5)", "profile.purposePlaceholder": "Selecciona",
    "users.title": "Buscar amigos", "users.filterAll": "Todos", "users.filterNearby": "Cerca", "users.filterTraining": "Entrenando", "users.filterCountry": "País", "users.filterHobby": "Afición", "users.filterPurpose": "Objetivo", "users.noUsers": "No se encontraron usuarios", "users.searchPlaceholder": "Buscar usuarios",
    "settings.title": "Ajustes", "settings.editProfile": "Editar perfil", "settings.editHobbies": "Editar aficiones", "settings.editPurpose": "Editar objetivo", "settings.notifications": "Notificaciones", "settings.language": "Idioma", "settings.darkMode": "Modo oscuro (próximamente)", "settings.logout": "Cerrar sesión", "settings.account": "Cuenta", "settings.preferences": "Preferencias",
    "messages.title": "Mensajes", "messages.all": "Todos", "messages.requests": "Solicitudes", "messages.empty": "No hay mensajes. ¡Inicia un DM desde un perfil!", "messages.emptyRequests": "No hay solicitudes", "messages.request": "Solicitud de mensaje", "messages.requestDesc": "te envió un mensaje. Acepta para empezar a chatear.", "messages.accept": "Aceptar", "messages.decline": "Eliminar", "messages.awaiting": "Esperando aprobación", "messages.blocked": "Bloqueaste a este usuario. No puedes enviar mensajes.", "messages.inputPlaceholder": "Escribe un mensaje…", "messages.cantSend": "No se pueden enviar mensajes", "messages.acceptToStart": "Acepta para empezar a chatear", "messages.awaitingShort": "Pendiente",
    "notifications.title": "Notificaciones", "notifications.empty": "No hay notificaciones",
    "home.heroTitle": "Entrena", "home.heroSub": "Conéctate en vivo, comparte ubicación y compite en el ranking.", "home.record": "Registrar entrenamiento", "home.viewLive": "Ver en vivo", "home.liveNow": "Entrenando ahora", "home.trainingNow": "TRAINING NOW", "home.noLive": "Nadie entrenando ahora. ¡Sé el primero!", "home.leaderboard": "Top rankers", "home.recent": "Registros recientes", "home.totalVolume": "Volumen total", "home.weekRecords": "Esta semana", "home.participants": "Participantes", "home.liveCount": "En vivo", "home.globe": "Globo mundial", "home.globeSub": "Mira quién entrena en el mundo. Ubicaciones difuminadas.", "home.trainingCount": "entrenando ahora", "home.noLiveMap": "Nadie entrenando ahora", "home.popularPosts": "Publicaciones populares", "home.noPosts": "Aún no hay publicaciones", "home.nearbyMap": "Mapa local", "home.nearbyMapSub": "Encuentra compañeros en todo el mundo. Verde = en línea, rojo = entrenando ahora. Toca un pin para ver el perfil.", "home.you": "Tú", "home.nearbyUser": "Usuario cercano", "home.trainingLive": "Entrenando ahora", "home.nearbyCount": "cerca", "home.worldView": "🌍 Mundo", "home.locateMe": "Ubicación actual", "home.satellite": "Satélite", "home.normalMap": "Mapa", "home.filter_all": "Todos", "home.filter_online": "En línea", "home.filter_training": "Entrenando", "home.filter_following": "Siguiendo", "home.filter_nearby": "Cercanos", "home.online": "En línea", "home.offline": "Desconectado",
    "auth.selectLanguage": "Selecciona idioma",     "auth.welcome": "Bienvenido a BELTVA",
    "hobby_cat_sports": "Deportes", "hobby_cat_games": "Juegos", "hobby_cat_music": "Música", "hobby_cat_anime": "Anime y cine", "hobby_cat_travel": "Viajes", "hobby_cat_reading": "Lectura", "hobby_cat_cafe": "Café", "hobby_cat_photo": "Foto", "hobby_cat_cooking": "Cocina", "hobby_cat_fashion": "Moda", "hobby_cat_car": "Coches", "hobby_cat_pet": "Mascotas",
    "purpose.hypertrophy": "Hipertrofia", "purpose.diet": "Dieta", "purpose.health": "Salud", "purpose.contest": "Competición", "purpose.friends": "Buscar amigos"
  },
  fr: {
    "nav.home": "Accueil", "nav.users": "Amis", "nav.messages": "Messages", "nav.timeline": "Fil", "nav.settings": "Réglages", "nav.goLive": "Démarrer",
    "common.back": "Retour", "common.save": "Enregistrer", "common.edit": "Modifier", "common.delete": "Supprimer", "common.cancel": "Annuler", "common.search": "Rechercher", "common.loading": "Chargement…", "common.online": "En ligne", "common.offline": "Hors ligne", "common.send": "Envoyer", "common.follow": "Suivre", "common.following": "Abonné", "common.message": "Message", "common.block": "Bloquer", "common.unblock": "Débloquer", "common.mute": "Muet", "common.unmute": "Réactiver", "common.report": "Signaler", "common.logout": "Déconnexion", "common.all": "Tous", "common.nearby": "À proximité", "common.trainingNow": "En entraînement", "common.country": "Pays", "common.hobbies": "Loisirs", "common.purpose": "Objectif", "common.bio": "Bio", "common.displayName": "Nom d'utilisateur", "common.selectCountry": "Choisir le pays",
    "profile.followers": "Abonnés", "profile.following": "Abonnements", "profile.posts": "Publications", "profile.noPosts": "Aucune publication", "profile.notFound": "Utilisateur introuvable", "profile.editTitle": "Modifier le profil", "profile.editAvatar": "Changer la photo", "profile.noAvatar": "Aucune", "profile.hobbiesMax": "Loisirs (max. 5)", "profile.purposePlaceholder": "Choisir",
    "users.title": "Trouver des amis", "users.filterAll": "Tous", "users.filterNearby": "À proximité", "users.filterTraining": "En entraînement", "users.filterCountry": "Pays", "users.filterHobby": "Loisir", "users.filterPurpose": "Objectif", "users.noUsers": "Aucun utilisateur trouvé", "users.searchPlaceholder": "Rechercher des utilisateurs",
    "settings.title": "Réglages", "settings.editProfile": "Modifier le profil", "settings.editHobbies": "Modifier les loisirs", "settings.editPurpose": "Modifier l'objectif", "settings.notifications": "Notifications", "settings.language": "Langue", "settings.darkMode": "Mode sombre (bientôt)", "settings.logout": "Déconnexion", "settings.account": "Compte", "settings.preferences": "Préférences",
    "messages.title": "Messages", "messages.all": "Tous", "messages.requests": "Demandes", "messages.empty": "Aucun message. Lance un DM depuis un profil !", "messages.emptyRequests": "Aucune demande", "messages.request": "Demande de message", "messages.requestDesc": "t'a envoyé un message. Accepte pour discuter.", "messages.accept": "Accepter", "messages.decline": "Supprimer", "messages.awaiting": "En attente d'approbation", "messages.blocked": "Tu as bloqué cet utilisateur. Impossible d'envoyer des messages.", "messages.inputPlaceholder": "Écris un message…", "messages.cantSend": "Envoi impossible", "messages.acceptToStart": "Accepte pour discuter", "messages.awaitingShort": "En attente",
    "notifications.title": "Notifications", "notifications.empty": "Aucune notification",
    "home.heroTitle": "Entraîne-toi", "home.heroSub": "Connecte-toi en live, partage ta position et défie-toi au classement.", "home.record": "Enregistrer la séance", "home.viewLive": "Voir le live", "home.liveNow": "Entraînement en cours", "home.trainingNow": "TRAINING NOW", "home.noLive": "Personne ne s'entraîne. Sois le premier !", "home.leaderboard": "Top rankers", "home.recent": "Records récents", "home.totalVolume": "Volume total", "home.weekRecords": "Cette semaine", "home.participants": "Participants", "home.liveCount": "En live", "home.globe": "Globe mondial", "home.globeSub": "Vois qui s'entraîne dans le monde. Positions floutées.", "home.trainingCount": "en entraînement", "home.noLiveMap": "Personne ne s'entraîne", "home.popularPosts": "Publications populaires", "home.noPosts": "Aucune publication", "home.nearbyMap": "Carte locale", "home.nearbyMapSub": "Trouve des partenaires partout dans le monde. Vert = en ligne, rouge = en entraînement. Touche un pin pour ouvrir le profil.", "home.you": "Toi", "home.nearbyUser": "Utilisateur proche", "home.trainingLive": "En entraînement", "home.nearbyCount": "à proximité", "home.worldView": "🌍 Monde", "home.locateMe": "Position actuelle", "home.satellite": "Satellite", "home.normalMap": "Carte", "home.filter_all": "Tous", "home.filter_online": "En ligne", "home.filter_training": "En entraînement", "home.filter_following": "Abonnements", "home.filter_nearby": "Proches", "home.online": "En ligne", "home.offline": "Hors ligne",
    "auth.selectLanguage": "Choisir la langue",     "auth.welcome": "Bienvenue sur BELTVA",
    "hobby_cat_sports": "Sport", "hobby_cat_games": "Jeux", "hobby_cat_music": "Musique", "hobby_cat_anime": "Anime et cinéma", "hobby_cat_travel": "Voyage", "hobby_cat_reading": "Lecture", "hobby_cat_cafe": "Café", "hobby_cat_photo": "Photo", "hobby_cat_cooking": "Cuisine", "hobby_cat_fashion": "Mode", "hobby_cat_car": "Auto", "hobby_cat_pet": "Animaux",
    "purpose.hypertrophy": "Hypertrophie", "purpose.diet": "Sèche", "purpose.health": "Santé", "purpose.contest": "Compétition", "purpose.friends": "Trouver des amis"
  },
  de: {
    "nav.home": "Start", "nav.users": "Freunde", "nav.messages": "Nachrichten", "nav.timeline": "Timeline", "nav.settings": "Einstellungen", "nav.goLive": "Starten",
    "common.back": "Zurück", "common.save": "Speichern", "common.edit": "Bearbeiten", "common.delete": "Löschen", "common.cancel": "Abbrechen", "common.search": "Suchen", "common.loading": "Lädt…", "common.online": "Online", "common.offline": "Offline", "common.send": "Senden", "common.follow": "Folgen", "common.following": "Folge ich", "common.message": "Nachricht", "common.block": "Blockieren", "common.unblock": "Entblocken", "common.mute": "Stummschalten", "common.unmute": "Lautschalten", "common.report": "Melden", "common.logout": "Abmelden", "common.all": "Alle", "common.nearby": "In der Nähe", "common.trainingNow": "Trainiert", "common.country": "Land", "common.hobbies": "Hobbys", "common.purpose": "Ziel", "common.bio": "Bio", "common.displayName": "Benutzername", "common.selectCountry": "Land wählen",
    "profile.followers": "Follower", "profile.following": "Folgt", "profile.posts": "Beiträge", "profile.noPosts": "Noch keine Beiträge", "profile.notFound": "Nutzer nicht gefunden", "profile.editTitle": "Profil bearbeiten", "profile.editAvatar": "Foto ändern", "profile.noAvatar": "Keins", "profile.hobbiesMax": "Hobbys (max. 5)", "profile.purposePlaceholder": "Wählen",
    "users.title": "Freunde finden", "users.filterAll": "Alle", "users.filterNearby": "In der Nähe", "users.filterTraining": "Trainiert", "users.filterCountry": "Land", "users.filterHobby": "Hobby", "users.filterPurpose": "Ziel", "users.noUsers": "Keine Nutzer gefunden", "users.searchPlaceholder": "Nutzer suchen",
    "settings.title": "Einstellungen", "settings.editProfile": "Profil bearbeiten", "settings.editHobbies": "Hobbys bearbeiten", "settings.editPurpose": "Ziel bearbeiten", "settings.notifications": "Benachrichtigungen", "settings.language": "Sprache", "settings.darkMode": "Dunkelmodus (bald)", "settings.logout": "Abmelden", "settings.account": "Konto", "settings.preferences": "Einstellungen",
    "messages.title": "Nachrichten", "messages.all": "Alle", "messages.requests": "Anfragen", "messages.empty": "Keine Nachrichten. Starte eine DM aus einem Profil!", "messages.emptyRequests": "Keine Anfragen", "messages.request": "Nachrichtenanfrage", "messages.requestDesc": "hat dir eine Nachricht gesendet. Akzeptieren zum Chatten.", "messages.accept": "Annehmen", "messages.decline": "Löschen", "messages.awaiting": "Wartet auf Bestätigung", "messages.blocked": "Du hast diesen Nutzer blockiert. Du kannst keine Nachrichten senden.", "messages.inputPlaceholder": "Nachricht schreiben…", "messages.cantSend": "Senden nicht möglich", "messages.acceptToStart": "Annehmen zum Chatten", "messages.awaitingShort": "Ausstehend",
    "notifications.title": "Benachrichtigungen", "notifications.empty": "Keine Benachrichtigungen",
    "home.heroTitle": "Trainiere", "home.heroSub": "Verbinde dich live, teile deinen Standort und trete im Ranking an.", "home.record": "Training protokollieren", "home.viewLive": "Live ansehen", "home.liveNow": "Trainiert jetzt", "home.trainingNow": "TRAINING NOW", "home.noLive": "Niemand trainiert gerade. Sei der Erste!", "home.leaderboard": "Top Rangliste", "home.recent": "Letzte Einträge", "home.totalVolume": "Gesamtvolumen", "home.weekRecords": "Diese Woche", "home.participants": "Teilnehmer", "home.liveCount": "Live", "home.globe": "Weltkugel", "home.globeSub": "Sieh, wer weltweit trainiert. Standorte verschwommen.", "home.trainingCount": "trainieren jetzt", "home.noLiveMap": "Niemand trainiert gerade", "home.popularPosts": "Beliebte Beiträge", "home.noPosts": "Noch keine Beiträge", "home.nearbyMap": "Lokale Karte", "home.nearbyMapSub": "Finde Partner weltweit. Grün = online, rot = trainiert jetzt. Tippe auf einen Pin fürs Profil.", "home.you": "Du", "home.nearbyUser": "Nutzer in der Nähe", "home.trainingLive": "Trainiert jetzt", "home.nearbyCount": "in der Nähe", "home.worldView": "🌍 Welt", "home.locateMe": "Aktueller Standort", "home.satellite": "Satellit", "home.normalMap": "Karte", "home.filter_all": "Alle", "home.filter_online": "Online", "home.filter_training": "Trainiert", "home.filter_following": "Folge ich", "home.filter_nearby": "In der Nähe", "home.online": "Online", "home.offline": "Offline",
    "auth.selectLanguage": "Sprache wählen",     "auth.welcome": "Willkommen bei BELTVA",
    "hobby_cat_sports": "Sport", "hobby_cat_games": "Spiele", "hobby_cat_music": "Musik", "hobby_cat_anime": "Anime & Film", "hobby_cat_travel": "Reisen", "hobby_cat_reading": "Lesen", "hobby_cat_cafe": "Café", "hobby_cat_photo": "Foto", "hobby_cat_cooking": "Kochen", "hobby_cat_fashion": "Mode", "hobby_cat_car": "Auto", "hobby_cat_pet": "Haustiere",
    "purpose.hypertrophy": "Muskelaufbau", "purpose.diet": "Diät", "purpose.health": "Gesundheit", "purpose.contest": "Wettkampf", "purpose.friends": "Freunde finden"
  },
  pt: {
    "nav.home": "Início", "nav.users": "Amigos", "nav.messages": "Mensagens", "nav.timeline": "Linha do tempo", "nav.settings": "Configurações", "nav.goLive": "Iniciar",
    "common.back": "Voltar", "common.save": "Salvar", "common.edit": "Editar", "common.delete": "Excluir", "common.cancel": "Cancelar", "common.search": "Buscar", "common.loading": "Carregando…", "common.online": "Online", "common.offline": "Offline", "common.send": "Enviar", "common.follow": "Seguir", "common.following": "Seguindo", "common.message": "Mensagem", "common.block": "Bloquear", "common.unblock": "Desbloquear", "common.mute": "Silenciar", "common.unmute": "Ativar", "common.report": "Denunciar", "common.logout": "Sair", "common.all": "Todos", "common.nearby": "Por perto", "common.trainingNow": "Treinando", "common.country": "País", "common.hobbies": "Hobbies", "common.purpose": "Objetivo", "common.bio": "Bio", "common.displayName": "Nome de usuário", "common.selectCountry": "Selecionar país",
    "profile.followers": "Seguidores", "profile.following": "Seguindo", "profile.posts": "Publicações", "profile.noPosts": "Ainda sem publicações", "profile.notFound": "Usuário não encontrado", "profile.editTitle": "Editar perfil", "profile.editAvatar": "Trocar foto", "profile.noAvatar": "Nenhuma", "profile.hobbiesMax": "Hobbies (máx. 5)", "profile.purposePlaceholder": "Selecionar",
    "users.title": "Encontrar amigos", "users.filterAll": "Todos", "users.filterNearby": "Por perto", "users.filterTraining": "Treinando", "users.filterCountry": "País", "users.filterHobby": "Hobby", "users.filterPurpose": "Objetivo", "users.noUsers": "Nenhum usuário encontrado", "users.searchPlaceholder": "Buscar usuários",
    "settings.title": "Configurações", "settings.editProfile": "Editar perfil", "settings.editHobbies": "Editar hobbies", "settings.editPurpose": "Editar objetivo", "settings.notifications": "Notificações", "settings.language": "Idioma", "settings.darkMode": "Modo escuro (em breve)", "settings.logout": "Sair", "settings.account": "Conta", "settings.preferences": "Preferências",
    "messages.title": "Mensagens", "messages.all": "Todas", "messages.requests": "Solicitações", "messages.empty": "Sem mensagens. Inicie um DM pelo perfil!", "messages.emptyRequests": "Sem solicitações", "messages.request": "Solicitação de mensagem", "messages.requestDesc": "te enviou uma mensagem. Aceite para conversar.", "messages.accept": "Aceitar", "messages.decline": "Excluir", "messages.awaiting": "Aguardando aprovação", "messages.blocked": "Você bloqueou este usuário. Não pode enviar mensagens.", "messages.inputPlaceholder": "Escreva uma mensagem…", "messages.cantSend": "Não é possível enviar", "messages.acceptToStart": "Aceite para conversar", "messages.awaitingShort": "Pendente",
    "notifications.title": "Notificações", "notifications.empty": "Sem notificações",
    "home.heroTitle": "Treine", "home.heroSub": "Conecte-se ao vivo, compartilhe a localização e compita no ranking.", "home.record": "Registrar treino", "home.viewLive": "Ver ao vivo", "home.liveNow": "Treinando agora", "home.trainingNow": "TRAINING NOW", "home.noLive": "Ninguém treinando agora. Seja o primeiro!", "home.leaderboard": "Top rankers", "home.recent": "Registros recentes", "home.totalVolume": "Volume total", "home.weekRecords": "Esta semana", "home.participants": "Participantes", "home.liveCount": "Ao vivo", "home.globe": "Globo mundial", "home.globeSub": "Veja quem treina pelo mundo. Localizações desfocadas.", "home.trainingCount": "treinando agora", "home.noLiveMap": "Ninguém treinando agora", "home.popularPosts": "Publicações populares", "home.noPosts": "Sem publicações", "home.nearbyMap": "Mapa local", "home.nearbyMapSub": "Encontre parceiros pelo mundo. Verde = online, vermelho = treinando agora. Toque num pin para ver o perfil.", "home.you": "Você", "home.nearbyUser": "Usuário próximo", "home.trainingLive": "Treinando agora", "home.nearbyCount": "por perto", "home.worldView": "🌍 Mundo", "home.locateMe": "Local atual", "home.satellite": "Satélite", "home.normalMap": "Mapa", "home.filter_all": "Todos", "home.filter_online": "Online", "home.filter_training": "Treinando", "home.filter_following": "Seguindo", "home.filter_nearby": "Próximos", "home.online": "Online", "home.offline": "Offline",
    "auth.selectLanguage": "Selecionar idioma",     "auth.welcome": "Bem-vindo ao BELTVA",
    "hobby_cat_sports": "Esportes", "hobby_cat_games": "Jogos", "hobby_cat_music": "Música", "hobby_cat_anime": "Anime e cinema", "hobby_cat_travel": "Viagens", "hobby_cat_reading": "Leitura", "hobby_cat_cafe": "Café", "hobby_cat_photo": "Foto", "hobby_cat_cooking": "Cozinha", "hobby_cat_fashion": "Moda", "hobby_cat_car": "Carros", "hobby_cat_pet": "Pets",
    "purpose.hypertrophy": "Hipertrofia", "purpose.diet": "Dieta", "purpose.health": "Saúde", "purpose.contest": "Competição", "purpose.friends": "Encontrar amigos"
  },
  it: {
    "nav.home": "Home", "nav.users": "Amici", "nav.messages": "Messaggi", "nav.timeline": "Timeline", "nav.settings": "Impostazioni", "nav.goLive": "Inizia",
    "common.back": "Indietro", "common.save": "Salva", "common.edit": "Modifica", "common.delete": "Elimina", "common.cancel": "Annulla", "common.search": "Cerca", "common.loading": "Caricamento…", "common.online": "Online", "common.offline": "Offline", "common.send": "Invia", "common.follow": "Segui", "common.following": "Seguendo", "common.message": "Messaggio", "common.block": "Blocca", "common.unblock": "Sblocca", "common.mute": "Silenzia", "common.unmute": "Riattiva", "common.report": "Segnala", "common.logout": "Esci", "common.all": "Tutti", "common.nearby": "Vicino", "common.trainingNow": "Allenamento", "common.country": "Paese", "common.hobbies": "Hobby", "common.purpose": "Obiettivo", "common.bio": "Bio", "common.displayName": "Nome utente", "common.selectCountry": "Seleziona paese",
    "profile.followers": "Follower", "profile.following": "Seguiti", "profile.posts": "Post", "profile.noPosts": "Nessun post", "profile.notFound": "Utente non trovato", "profile.editTitle": "Modifica profilo", "profile.editAvatar": "Cambia foto", "profile.noAvatar": "Nessuna", "profile.hobbiesMax": "Hobby (max 5)", "profile.purposePlaceholder": "Seleziona",
    "users.title": "Trova amici", "users.filterAll": "Tutti", "users.filterNearby": "Vicino", "users.filterTraining": "Allenamento", "users.filterCountry": "Paese", "users.filterHobby": "Hobby", "users.filterPurpose": "Obiettivo", "users.noUsers": "Nessun utente trovato", "users.searchPlaceholder": "Cerca utenti",
    "settings.title": "Impostazioni", "settings.editProfile": "Modifica profilo", "settings.editHobbies": "Modifica hobby", "settings.editPurpose": "Modifica obiettivo", "settings.notifications": "Notifiche", "settings.language": "Lingua", "settings.darkMode": "Modalità scura (prossimamente)", "settings.logout": "Esci", "settings.account": "Account", "settings.preferences": "Preferenze",
    "messages.title": "Messaggi", "messages.all": "Tutti", "messages.requests": "Richieste", "messages.empty": "Nessun messaggio. Inizia un DM dal profilo!", "messages.emptyRequests": "Nessuna richiesta", "messages.request": "Richiesta di messaggio", "messages.requestDesc": "ti ha inviato un messaggio. Accetta per chattare.", "messages.accept": "Accetta", "messages.decline": "Elimina", "messages.awaiting": "In attesa di approvazione", "messages.blocked": "Hai bloccato questo utente. Non puoi inviare messaggi.", "messages.inputPlaceholder": "Scrivi un messaggio…", "messages.cantSend": "Impossibile inviare", "messages.acceptToStart": "Accetta per chattare", "messages.awaitingShort": "In attesa",
    "notifications.title": "Notifiche", "notifications.empty": "Nessuna notifica",
    "home.heroTitle": "Allenati", "home.heroSub": "Connettiti in live, condividi la posizione e gareggia in classifica.", "home.record": "Registra allenamento", "home.viewLive": "Guarda live", "home.liveNow": "Allenamento in corso", "home.trainingNow": "TRAINING NOW", "home.noLive": "Nessuno si allena ora. Sii il primo!", "home.leaderboard": "Top ranker", "home.recent": "Record recenti", "home.totalVolume": "Volume totale", "home.weekRecords": "Questa settimana", "home.participants": "Partecipanti", "home.liveCount": "Live", "home.globe": "Globo mondiale", "home.globeSub": "Vedi chi si allena nel mondo. Posizioni sfocate.", "home.trainingCount": "si allenano ora", "home.noLiveMap": "Nessuno si allena ora", "home.popularPosts": "Post popolari", "home.noPosts": "Nessun post", "home.nearbyMap": "Mappa locale", "home.nearbyMapSub": "Trova partner in tutto il mondo. Verde = online, rosso = in allenamento. Tocca un pin per il profilo.", "home.you": "Tu", "home.nearbyUser": "Utente vicino", "home.trainingLive": "In allenamento", "home.nearbyCount": "vicini", "home.worldView": "🌍 Mondo", "home.locateMe": "Posizione attuale", "home.satellite": "Satellitare", "home.normalMap": "Mappa", "home.filter_all": "Tutti", "home.filter_online": "Online", "home.filter_training": "In allenamento", "home.filter_following": "Seguiti", "home.filter_nearby": "Vicini", "home.online": "Online", "home.offline": "Offline",
    "auth.selectLanguage": "Seleziona lingua",     "auth.welcome": "Benvenuto su BELTVA",
    "hobby_cat_sports": "Sport", "hobby_cat_games": "Giochi", "hobby_cat_music": "Musica", "hobby_cat_anime": "Anime e cinema", "hobby_cat_travel": "Viaggi", "hobby_cat_reading": "Lettura", "hobby_cat_cafe": "Caffè", "hobby_cat_photo": "Foto", "hobby_cat_cooking": "Cucina", "hobby_cat_fashion": "Moda", "hobby_cat_car": "Auto", "hobby_cat_pet": "Animali",
    "purpose.hypertrophy": "Ipertrofia", "purpose.diet": "Dieta", "purpose.health": "Salute", "purpose.contest": "Gara", "purpose.friends": "Trova amici"
  },
  ru: {
    "nav.home": "Главная", "nav.users": "Друзья", "nav.messages": "Сообщения", "nav.timeline": "Лента", "nav.settings": "Настройки", "nav.goLive": "Старт",
    "common.back": "Назад", "common.save": "Сохранить", "common.edit": "Изменить", "common.delete": "Удалить", "common.cancel": "Отмена", "common.search": "Поиск", "common.loading": "Загрузка…", "common.online": "Онлайн", "common.offline": "Офлайн", "common.send": "Отправить", "common.follow": "Подписаться", "common.following": "Вы подписаны", "common.message": "Сообщение", "common.block": "Заблокировать", "common.unblock": "Разблокировать", "common.mute": "Игнорировать", "common.unmute": "Включить", "common.report": "Пожаловаться", "common.logout": "Выйти", "common.all": "Все", "common.nearby": "Рядом", "common.trainingNow": "Тренируется", "common.country": "Страна", "common.hobbies": "Хобби", "common.purpose": "Цель", "common.bio": "О себе", "common.displayName": "Имя пользователя", "common.selectCountry": "Выберите страну",
    "profile.followers": "Подписчики", "profile.following": "Подписки", "profile.posts": "Публикации", "profile.noPosts": "Пока нет публикаций", "profile.notFound": "Пользователь не найден", "profile.editTitle": "Редактировать профиль", "profile.editAvatar": "Сменить фото", "profile.noAvatar": "Нет", "profile.hobbiesMax": "Хобби (макс. 5)", "profile.purposePlaceholder": "Выберите",
    "users.title": "Найти друзей", "users.filterAll": "Все", "users.filterNearby": "Рядом", "users.filterTraining": "Тренируется", "users.filterCountry": "Страна", "users.filterHobby": "Хобби", "users.filterPurpose": "Цель", "users.noUsers": "Пользователи не найдены", "users.searchPlaceholder": "Поиск пользователей",
    "settings.title": "Настройки", "settings.editProfile": "Редактировать профиль", "settings.editHobbies": "Редактировать хобби", "settings.editPurpose": "Изменить цель", "settings.notifications": "Уведомления", "settings.language": "Язык", "settings.darkMode": "Тёмная тема (скоро)", "settings.logout": "Выйти", "settings.account": "Аккаунт", "settings.preferences": "Параметры",
    "messages.title": "Сообщения", "messages.all": "Все", "messages.requests": "Запросы", "messages.empty": "Нет сообщений. Начните диалог из профиля!", "messages.emptyRequests": "Нет запросов", "messages.request": "Запрос на сообщение", "messages.requestDesc": "отправил вам сообщение. Примите, чтобы начать чат.", "messages.accept": "Принять", "messages.decline": "Удалить", "messages.awaiting": "Ожидание подтверждения", "messages.blocked": "Вы заблокировали этого пользователя. Сообщения недоступны.", "messages.inputPlaceholder": "Введите сообщение…", "messages.cantSend": "Отправка недоступна", "messages.acceptToStart": "Примите, чтобы начать чат", "messages.awaitingShort": "Ожидание",
    "notifications.title": "Уведомления", "notifications.empty": "Нет уведомлений",
    "home.heroTitle": "Тренируйся", "home.heroSub": "Подключайся в эфире, делись геолокацией и соревнуйся в рейтинге.", "home.record": "Записать тренировку", "home.viewLive": "Смотреть эфир", "home.liveNow": "Тренируется сейчас", "home.trainingNow": "TRAINING NOW", "home.noLive": "Сейчас никто не тренируется. Будь первым!", "home.leaderboard": "Топ рейтинга", "home.recent": "Недавние записи", "home.totalVolume": "Общий объём", "home.weekRecords": "На этой неделе", "home.participants": "Участники", "home.liveCount": "В эфире", "home.globe": "Глобус", "home.globeSub": "Кто тренируется в мире. Геолокации размыты.", "home.trainingCount": "тренируются сейчас", "home.noLiveMap": "Сейчас никто не тренируется", "home.popularPosts": "Популярные посты", "home.noPosts": "Пока нет публикаций", "home.nearbyMap": "Локальная карта", "home.nearbyMapSub": "Находи партнёров по всему миру. Зелёный = онлайн, красный = тренируется сейчас. Нажми на маркер для профиля.", "home.you": "Вы", "home.nearbyUser": "Пользователь рядом", "home.trainingLive": "Тренируется сейчас", "home.nearbyCount": "рядом", "home.worldView": "🌍 Мир", "home.locateMe": "Текущее местоположение", "home.satellite": "Спутник", "home.normalMap": "Карта", "home.filter_all": "Все", "home.filter_online": "Онлайн", "home.filter_training": "Тренируется", "home.filter_following": "Подписки", "home.filter_nearby": "Рядом", "home.online": "Онлайн", "home.offline": "Не в сети",
    "auth.selectLanguage": "Выберите язык",     "auth.welcome": "Добро пожаловать в BELTVA",
    "hobby_cat_sports": "Спорт", "hobby_cat_games": "Игры", "hobby_cat_music": "Музыка", "hobby_cat_anime": "Аниме и кино", "hobby_cat_travel": "Путешествия", "hobby_cat_reading": "Чтение", "hobby_cat_cafe": "Кафе", "hobby_cat_photo": "Фото", "hobby_cat_cooking": "Кулинария", "hobby_cat_fashion": "Мода", "hobby_cat_car": "Авто", "hobby_cat_pet": "Питомцы",
    "purpose.hypertrophy": "Гипертрофия", "purpose.diet": "Сушка", "purpose.health": "Здоровье", "purpose.contest": "Соревнования", "purpose.friends": "Найти друзей"
  },
  vi: {
    "nav.home": "Trang chủ", "nav.users": "Bạn bè", "nav.messages": "Tin nhắn", "nav.timeline": "Bảng tin", "nav.settings": "Cài đặt", "nav.goLive": "Bắt đầu",
    "common.back": "Quay lại", "common.save": "Lưu", "common.edit": "Sửa", "common.delete": "Xoá", "common.cancel": "Huỷ", "common.search": "Tìm kiếm", "common.loading": "Đang tải…", "common.online": "Trực tuyến", "common.offline": "Ngoại tuyến", "common.send": "Gửi", "common.follow": "Theo dõi", "common.following": "Đang theo dõi", "common.message": "Tin nhắn", "common.block": "Chặn", "common.unblock": "Bỏ chặn", "common.mute": "Tắt thông báo", "common.unmute": "Bật thông báo", "common.report": "Báo cáo", "common.logout": "Đăng xuất", "common.all": "Tất cả", "common.nearby": "Gần đây", "common.trainingNow": "Đang tập", "common.country": "Quốc gia", "common.hobbies": "Sở thích", "common.purpose": "Mục tiêu", "common.bio": "Tiểu sử", "common.displayName": "Tên người dùng", "common.selectCountry": "Chọn quốc gia",
    "profile.followers": "Người theo dõi", "profile.following": "Đang theo dõi", "profile.posts": "Bài viết", "profile.noPosts": "Chưa có bài viết", "profile.notFound": "Không tìm thấy người dùng", "profile.editTitle": "Sửa hồ sơ", "profile.editAvatar": "Đổi ảnh", "profile.noAvatar": "Không", "profile.hobbiesMax": "Sở thích (tối đa 5)", "profile.purposePlaceholder": "Chọn",
    "users.title": "Tìm bạn bè", "users.filterAll": "Tất cả", "users.filterNearby": "Gần đây", "users.filterTraining": "Đang tập", "users.filterCountry": "Quốc gia", "users.filterHobby": "Sở thích", "users.filterPurpose": "Mục tiêu", "users.noUsers": "Không tìm thấy người dùng", "users.searchPlaceholder": "Tìm người dùng",
    "settings.title": "Cài đặt", "settings.editProfile": "Sửa hồ sơ", "settings.editHobbies": "Sửa sở thích", "settings.editPurpose": "Sửa mục tiêu", "settings.notifications": "Thông báo", "settings.language": "Ngôn ngữ", "settings.darkMode": "Chế độ tối (sắp có)", "settings.logout": "Đăng xuất", "settings.account": "Tài khoản", "settings.preferences": "Tuỳ chọn",
    "messages.title": "Tin nhắn", "messages.all": "Tất cả", "messages.requests": "Yêu cầu", "messages.empty": "Không có tin nhắn. Hãy bắt đầu DM từ hồ sơ!", "messages.emptyRequests": "Không có yêu cầu", "messages.request": "Yêu cầu tin nhắn", "messages.requestDesc": "đã gửi bạn tin nhắn. Chấp nhận để bắt đầu trò chuyện.", "messages.accept": "Chấp nhận", "messages.decline": "Xoá", "messages.awaiting": "Đang chờ chấp nhận", "messages.blocked": "Bạn đã chặn người dùng này. Không thể gửi tin nhắn.", "messages.inputPlaceholder": "Nhập tin nhắn…", "messages.cantSend": "Không thể gửi", "messages.acceptToStart": "Chấp nhận để trò chuyện", "messages.awaitingShort": "Đang chờ",
    "notifications.title": "Thông báo", "notifications.empty": "Không có thông báo",
    "home.heroTitle": "Tập luyện thôi", "home.heroSub": "Kết nối trực tiếp, chia sẻ vị trí và thi đấu trên bảng xếp hạng.", "home.record": "Ghi nhận tập luyện", "home.viewLive": "Xem trực tiếp", "home.liveNow": "Đang tập", "home.trainingNow": "TRAINING NOW", "home.noLive": "Chưa ai tập lúc này. Hãy là người đầu tiên!", "home.leaderboard": "Top xếp hạng", "home.recent": "Ghi nhận gần đây", "home.totalVolume": "Tổng khối lượng", "home.weekRecords": "Tuần này", "home.participants": "Người tham gia", "home.liveCount": "Trực tiếp", "home.globe": "Quả cầu", "home.globeSub": "Xem ai đang tập trên thế giới. Vị trí được làm mờ.", "home.trainingCount": "đang tập", "home.noLiveMap": "Chưa ai tập lúc này", "home.popularPosts": "Bài viết phổ biến", "home.noPosts": "Chưa có bài viết", "home.nearbyMap": "Bản đồ địa phương", "home.nearbyMapSub": "Tìm bạn tập trên toàn thế giới. Xanh = trực tuyến, đỏ = đang tập. Chạm ghim để xem hồ sơ.", "home.you": "Bạn", "home.nearbyUser": "Người dùng gần đây", "home.trainingLive": "Đang tập", "home.nearbyCount": "người gần đây", "home.worldView": "🌍 Thế giới", "home.locateMe": "Vị trí hiện tại", "home.satellite": "Vệ tinh", "home.normalMap": "Bản đồ", "home.filter_all": "Tất cả", "home.filter_online": "Trực tuyến", "home.filter_training": "Đang tập", "home.filter_following": "Đang theo dõi", "home.filter_nearby": "Gần đây", "home.online": "Trực tuyến", "home.offline": "Ngoại tuyến",
    "auth.selectLanguage": "Chọn ngôn ngữ",     "auth.welcome": "Chào mừng đến BELTVA",
    "hobby_cat_sports": "Thể thao", "hobby_cat_games": "Trò chơi", "hobby_cat_music": "Âm nhạc", "hobby_cat_anime": "Anime & phim", "hobby_cat_travel": "Du lịch", "hobby_cat_reading": "Đọc sách", "hobby_cat_cafe": "Cafe", "hobby_cat_photo": "Nhiếp ảnh", "hobby_cat_cooking": "Nấu ăn", "hobby_cat_fashion": "Thời trang", "hobby_cat_car": "Ô tô", "hobby_cat_pet": "Thú cưng",
    "purpose.hypertrophy": "Tăng cơ", "purpose.diet": "Giảm mỡ", "purpose.health": "Sức khoẻ", "purpose.contest": "Thi đấu", "purpose.friends": "Tìm bạn"
  },
  id: {
    "nav.home": "Beranda", "nav.users": "Teman", "nav.messages": "Pesan", "nav.timeline": "Linimasa", "nav.settings": "Pengaturan", "nav.goLive": "Mulai",
    "common.back": "Kembali", "common.save": "Simpan", "common.edit": "Edit", "common.delete": "Hapus", "common.cancel": "Batal", "common.search": "Cari", "common.loading": "Memuat…", "common.online": "Online", "common.offline": "Offline", "common.send": "Kirim", "common.follow": "Ikuti", "common.following": "Mengikuti", "common.message": "Pesan", "common.block": "Blokir", "common.unblock": "Buka blokir", "common.mute": "Bisukan", "common.unmute": "Bunyikan", "common.report": "Laporkan", "common.logout": "Keluar", "common.all": "Semua", "common.nearby": "Terdekat", "common.trainingNow": "Latihan", "common.country": "Negara", "common.hobbies": "Hobi", "common.purpose": "Tujuan", "common.bio": "Bio", "common.displayName": "Nama pengguna", "common.selectCountry": "Pilih negara",
    "profile.followers": "Pengikut", "profile.following": "Mengikuti", "profile.posts": "Postingan", "profile.noPosts": "Belum ada postingan", "profile.notFound": "Pengguna tidak ditemukan", "profile.editTitle": "Edit profil", "profile.editAvatar": "Ganti foto", "profile.noAvatar": "Tidak ada", "profile.hobbiesMax": "Hobi (maks. 5)", "profile.purposePlaceholder": "Pilih",
    "users.title": "Cari teman", "users.filterAll": "Semua", "users.filterNearby": "Terdekat", "users.filterTraining": "Latihan", "users.filterCountry": "Negara", "users.filterHobby": "Hobi", "users.filterPurpose": "Tujuan", "users.noUsers": "Pengguna tidak ditemukan", "users.searchPlaceholder": "Cari pengguna",
    "settings.title": "Pengaturan", "settings.editProfile": "Edit profil", "settings.editHobbies": "Edit hobi", "settings.editPurpose": "Edit tujuan", "settings.notifications": "Notifikasi", "settings.language": "Bahasa", "settings.darkMode": "Mode gelap (segera)", "settings.logout": "Keluar", "settings.account": "Akun", "settings.preferences": "Preferensi",
    "messages.title": "Pesan", "messages.all": "Semua", "messages.requests": "Permintaan", "messages.empty": "Tidak ada pesan. Mulai DM dari profil!", "messages.emptyRequests": "Tidak ada permintaan", "messages.request": "Permintaan pesan", "messages.requestDesc": "mengirim pesan. Terima untuk mulai mengobrol.", "messages.accept": "Terima", "messages.decline": "Hapus", "messages.awaiting": "Menunggu persetujuan", "messages.blocked": "Anda memblokir pengguna ini. Tidak bisa mengirim pesan.", "messages.inputPlaceholder": "Tulis pesan…", "messages.cantSend": "Tidak bisa mengirim", "messages.acceptToStart": "Terima untuk mengobrol", "messages.awaitingShort": "Menunggu",
    "notifications.title": "Notifikasi", "notifications.empty": "Tidak ada notifikasi",
    "home.heroTitle": "Berlatih", "home.heroSub": "Terhubung live, bagikan lokasi, dan bersaing di peringkat.", "home.record": "Catat latihan", "home.viewLive": "Tonton live", "home.liveNow": "Latihan sekarang", "home.trainingNow": "TRAINING NOW", "home.noLive": "Tidak ada yang latihan. Jadilah yang pertama!", "home.leaderboard": "Top peringkat", "home.recent": "Catatan terbaru", "home.totalVolume": "Total volume", "home.weekRecords": "Minggu ini", "home.participants": "Peserta", "home.liveCount": "Live", "home.globe": "Globe dunia", "home.globeSub": "Lihat siapa latihan di dunia. Lokasi diburamkan.", "home.trainingCount": "latihan sekarang", "home.noLiveMap": "Tidak ada yang latihan", "home.popularPosts": "Postingan populer", "home.noPosts": "Belum ada postingan", "home.nearbyMap": "Peta lokal", "home.nearbyMapSub": "Temukan partner di seluruh dunia. Hijau = online, merah = sedang latihan. Ketuk pin untuk profil.", "home.you": "Anda", "home.nearbyUser": "Pengguna terdekat", "home.trainingLive": "Sedang latihan", "home.nearbyCount": "di dekat sini", "home.worldView": "🌍 Dunia", "home.locateMe": "Lokasi saat ini", "home.satellite": "Satelit", "home.normalMap": "Peta", "home.filter_all": "Semua", "home.filter_online": "Online", "home.filter_training": "Sedang latihan", "home.filter_following": "Mengikuti", "home.filter_nearby": "Terdekat", "home.online": "Online", "home.offline": "Offline",
    "auth.selectLanguage": "Pilih bahasa",     "auth.welcome": "Selamat datang di BELTVA",
    "hobby_cat_sports": "Olahraga", "hobby_cat_games": "Game", "hobby_cat_music": "Musik", "hobby_cat_anime": "Anime & film", "hobby_cat_travel": "Jalan-jalan", "hobby_cat_reading": "Membaca", "hobby_cat_cafe": "Kafe", "hobby_cat_photo": "Foto", "hobby_cat_cooking": "Memasak", "hobby_cat_fashion": "Mode", "hobby_cat_car": "Mobil", "hobby_cat_pet": "Hewan peliharaan",
    "purpose.hypertrophy": "Hipertrofi", "purpose.diet": "Diet", "purpose.health": "Kesehatan", "purpose.contest": "Kompetisi", "purpose.friends": "Cari teman"
  },
  th: {
    "nav.home": "หน้าหลัก", "nav.users": "เพื่อน", "nav.messages": "ข้อความ", "nav.timeline": "ไทม์ไลน์", "nav.settings": "ตั้งค่า", "nav.goLive": "เริ่ม",
    "common.back": "ย้อนกลับ", "common.save": "บันทึก", "common.edit": "แก้ไข", "common.delete": "ลบ", "common.cancel": "ยกเลิก", "common.search": "ค้นหา", "common.loading": "กำลังโหลด…", "common.online": "ออนไลน์", "common.offline": "ออฟไลน์", "common.send": "ส่ง", "common.follow": "ติดตาม", "common.following": "กำลังติดตาม", "common.message": "ข้อความ", "common.block": "บล็อก", "common.unblock": "ปลดบล็อก", "common.mute": "ปิดแจ้งเตือน", "common.unmute": "เปิดแจ้งเตือน", "common.report": "รายงาน", "common.logout": "ออกจากระบบ", "common.all": "ทั้งหมด", "common.nearby": "ใกล้เคียง", "common.trainingNow": "กำลังฝึก", "common.country": "ประเทศ", "common.hobbies": "งานอดิเรก", "common.purpose": "เป้าหมาย", "common.bio": "แนะนำตัว", "common.displayName": "ชื่อผู้ใช้", "common.selectCountry": "เลือกประเทศ",
    "profile.followers": "ผู้ติดตาม", "profile.following": "กำลังติดตาม", "profile.posts": "โพสต์", "profile.noPosts": "ยังไม่มีโพสต์", "profile.notFound": "ไม่พบผู้ใช้", "profile.editTitle": "แก้ไขโปรไฟล์", "profile.editAvatar": "เปลี่ยนรูป", "profile.noAvatar": "ไม่มี", "profile.hobbiesMax": "งานอดิเรก (สูงสุด 5)", "profile.purposePlaceholder": "เลือก",
    "users.title": "หาเพื่อน", "users.filterAll": "ทั้งหมด", "users.filterNearby": "ใกล้เคียง", "users.filterTraining": "กำลังฝึก", "users.filterCountry": "ประเทศ", "users.filterHobby": "งานอดิเรก", "users.filterPurpose": "เป้าหมาย", "users.noUsers": "ไม่พบผู้ใช้", "users.searchPlaceholder": "ค้นหาผู้ใช้",
    "settings.title": "ตั้งค่า", "settings.editProfile": "แก้ไขโปรไฟล์", "settings.editHobbies": "แก้ไขงานอดิเรก", "settings.editPurpose": "แก้ไขเป้าหมาย", "settings.notifications": "การแจ้งเตือน", "settings.language": "ภาษา", "settings.darkMode": "โหมดมืด (เร็วๆ นี้)", "settings.logout": "ออกจากระบบ", "settings.account": "บัญชี", "settings.preferences": "การตั้งค่า",
    "messages.title": "ข้อความ", "messages.all": "ทั้งหมด", "messages.requests": "คำขอ", "messages.empty": "ไม่มีข้อความ เริ่ม DM จากโปรไฟล์ได้เลย!", "messages.emptyRequests": "ไม่มีคำขอ", "messages.request": "คำขอข้อความ", "messages.requestDesc": "ส่งข้อความถึงคุณ ยอมรับเพื่อเริ่มแชต", "messages.accept": "ยอมรับ", "messages.decline": "ลบ", "messages.awaiting": "รอการยอมรับ", "messages.blocked": "คุณบล็อกผู้ใช้นี้ ไม่สามารถส่งข้อความได้", "messages.inputPlaceholder": "พิมพ์ข้อความ…", "messages.cantSend": "ส่งไม่ได้", "messages.acceptToStart": "ยอมรับเพื่อเริ่มแชต", "messages.awaitingShort": "รออยู่",
    "notifications.title": "การแจ้งเตือน", "notifications.empty": "ไม่มีการแจ้งเตือน",
    "home.heroTitle": "ออกกำลังกายกัน", "home.heroSub": "เชื่อมต่อสด แชร์ตำแหน่ง และแข่งขันในอันดับ", "home.record": "บันทึกการออกกำลังกาย", "home.viewLive": "ดูสด", "home.liveNow": "กำลังฝึกอยู่", "home.trainingNow": "TRAINING NOW", "home.noLive": "ยังไม่มีใครฝึก มาเป็นคนแรกเลย!", "home.leaderboard": "อันดับสูงสุด", "home.recent": "บันทึกล่าสุด", "home.totalVolume": "ปริมาณรวม", "home.weekRecords": "สัปดาห์นี้", "home.participants": "ผู้เข้าร่วม", "home.liveCount": "สด", "home.globe": "ลูกโลก", "home.globeSub": "ดูว่าใครกำลังฝึกทั่วโลก ตำแหน่งถูกเบลอ", "home.trainingCount": "กำลังฝึก", "home.noLiveMap": "ยังไม่มีใครฝึก", "home.popularPosts": "โพสต์ยอดนิยม", "home.noPosts": "ยังไม่มีโพสต์", "home.nearbyMap": "แผนที่ท้องถิ่น", "home.nearbyMapSub": "หาเพื่อนฝึกทั่วโลก เขียว=ออนไลน์ แดง=กำลังฝึก แตะหมุดเพื่อดูโปรไฟล์", "home.you": "คุณ", "home.nearbyUser": "ผู้ใช้ใกล้เคียง", "home.trainingLive": "กำลังฝึก", "home.nearbyCount": "คนใกล้คุณ", "home.worldView": "🌍 โลก", "home.locateMe": "ตำแหน่งปัจจุบัน", "home.satellite": "ดาวเทียม", "home.normalMap": "แผนที่", "home.filter_all": "ทั้งหมด", "home.filter_online": "ออนไลน์", "home.filter_training": "กำลังฝึก", "home.filter_following": "ติดตามอยู่", "home.filter_nearby": "ใกล้เคียง", "home.online": "ออนไลน์", "home.offline": "ออฟไลน์",
    "auth.selectLanguage": "เลือกภาษา",     "auth.welcome": "ยินดีต้อนรับสู่ BELTVA",
    "hobby_cat_sports": "กีฬา", "hobby_cat_games": "เกม", "hobby_cat_music": "ดนตรี", "hobby_cat_anime": "อนิเมะและภาพยนตร์", "hobby_cat_travel": "ท่องเที่ยว", "hobby_cat_reading": "อ่านหนังสือ", "hobby_cat_cafe": "คาเฟ่", "hobby_cat_photo": "ถ่ายภาพ", "hobby_cat_cooking": "ทำอาหาร", "hobby_cat_fashion": "แฟชั่น", "hobby_cat_car": "รถยนต์", "hobby_cat_pet": "สัตว์เลี้ยง",
    "purpose.hypertrophy": "สร้างกล้าม", "purpose.diet": "ลดน้ำหนัก", "purpose.health": "สุขภาพ", "purpose.contest": "แข่งขัน", "purpose.friends": "หาเพื่อน"
  },
  hi: {
    "nav.home": "होम", "nav.users": "दोस्त", "nav.messages": "संदेश", "nav.timeline": "टाइमलाइन", "nav.settings": "सेटिंग्स", "nav.goLive": "शुरू करें",
    "common.back": "वापस", "common.save": "सहेजें", "common.edit": "संपादित करें", "common.delete": "हटाएँ", "common.cancel": "रद्द करें", "common.search": "खोजें", "common.loading": "लोड हो रहा है…", "common.online": "ऑनलाइन", "common.offline": "ऑफ़लाइन", "common.send": "भेजें", "common.follow": "फ़ॉलो", "common.following": "फ़ॉलोइंग", "common.message": "संदेश", "common.block": "ब्लॉक", "common.unblock": "अनब्लॉक", "common.mute": "म्यूट", "common.unmute": "अनम्यूट", "common.report": "रिपोर्ट", "common.logout": "लॉग आउट", "common.all": "सभी", "common.nearby": "पास में", "common.trainingNow": "प्रशिक्षण", "common.country": "देश", "common.hobbies": "शौक", "common.purpose": "लक्ष्य", "common.bio": "परिचय", "common.displayName": "यूज़रनेम", "common.selectCountry": "देश चुनें",
    "profile.followers": "फ़ॉलोअर", "profile.following": "फ़ॉलोइंग", "profile.posts": "पोस्ट", "profile.noPosts": "अभी कोई पोस्ट नहीं", "profile.notFound": "यूज़र नहीं मिला", "profile.editTitle": "प्रोफ़ाइल संपादित करें", "profile.editAvatar": "फ़ोटो बदलें", "profile.noAvatar": "कोई नहीं", "profile.hobbiesMax": "शौक (अधिकतम 5)", "profile.purposePlaceholder": "चुनें",
    "users.title": "दोस्त खोजें", "users.filterAll": "सभी", "users.filterNearby": "पास में", "users.filterTraining": "प्रशिक्षण", "users.filterCountry": "देश", "users.filterHobby": "शौक", "users.filterPurpose": "लक्ष्य", "users.noUsers": "कोई यूज़र नहीं मिला", "users.searchPlaceholder": "यूज़र खोजें",
    "settings.title": "सेटिंग्स", "settings.editProfile": "प्रोफ़ाइल संपादित करें", "settings.editHobbies": "शौक संपादित करें", "settings.editPurpose": "लक्ष्य संपादित करें", "settings.notifications": "सूचनाएँ", "settings.language": "भाषा", "settings.darkMode": "डार्क मोड (जल्दी)", "settings.logout": "लॉग आउट", "settings.account": "खाता", "settings.preferences": "प्राथमिकताएँ",
    "messages.title": "संदेश", "messages.all": "सभी", "messages.requests": "अनुरोध", "messages.empty": "कोई संदेश नहीं। प्रोफ़ाइल से DM शुरू करें!", "messages.emptyRequests": "कोई अनुरोध नहीं", "messages.request": "संदेश अनुरोध", "messages.requestDesc": "ने संदेश भेजा है। चैट शुरू करने के लिए स्वीकार करें।", "messages.accept": "स्वीकार", "messages.decline": "हटाएँ", "messages.awaiting": "स्वीकृति की प्रतीक्षा", "messages.blocked": "आपने इस यूज़र को ब्लॉक किया है। संदेश नहीं भेज सकते।", "messages.inputPlaceholder": "संदेश लिखें…", "messages.cantSend": "भेज नहीं सकते", "messages.acceptToStart": "चैट शुरू करने के लिए स्वीकार करें", "messages.awaitingShort": "लंबित",
    "notifications.title": "सूचनाएँ", "notifications.empty": "कोई सूचना नहीं",
    "home.heroTitle": "प्रशिक्षण शुरू करें", "home.heroSub": "लाइव कनेक्ट करें, स्थान साझा करें और रैंकिंग में प्रतिस्पर्धा करें।", "home.record": "प्रशिक्षण दर्ज करें", "home.viewLive": "लाइव देखें", "home.liveNow": "अभी प्रशिक्षण", "home.trainingNow": "TRAINING NOW", "home.noLive": "अभी कोई प्रशिक्षण नहीं। पहले बनें!", "home.leaderboard": "टॉप रैंकर", "home.recent": "हाल के रिकॉर्ड", "home.totalVolume": "कुल वॉल्यूम", "home.weekRecords": "इस सप्ताह", "home.participants": "प्रतिभागी", "home.liveCount": "लाइव", "home.globe": "विश्व ग्लोब", "home.globeSub": "देखें कौन दुनिया में प्रशिक्षण कर रहा है। स्थान धुंधले हैं।", "home.trainingCount": "प्रशिक्षण में", "home.noLiveMap": "अभी कोई प्रशिक्षण नहीं", "home.popularPosts": "लोकप्रिय पोस्ट", "home.noPosts": "अभी कोई पोस्ट नहीं", "home.nearbyMap": "स्थानीय नक्शा", "home.nearbyMapSub": "पूरे विश्व में पार्टनर खोजें। हरा=ऑनलाइन, लाल=अभी प्रशिक्षण। पिन टैप कर प्रोफ़ाइल खोलें।", "home.you": "आप", "home.nearbyUser": "पास का यूज़र", "home.trainingLive": "अभी प्रशिक्षण", "home.nearbyCount": "पास में", "home.worldView": "🌍 विश्व", "home.locateMe": "वर्तमान स्थान", "home.satellite": "उपग्रह", "home.normalMap": "नक्शा", "home.filter_all": "सभी", "home.filter_online": "ऑनलाइन", "home.filter_training": "प्रशिक्षण", "home.filter_following": "फ़ॉलोइंग", "home.filter_nearby": "पास के", "home.online": "ऑनलाइन", "home.offline": "ऑफ़लाइन",
    "auth.selectLanguage": "भाषा चुनें",     "auth.welcome": "BELTVA में आपका स्वागत है",
    "hobby_cat_sports": "खेल", "hobby_cat_games": "गेम्स", "hobby_cat_music": "संगीत", "hobby_cat_anime": "एनिमे और फ़िल्म", "hobby_cat_travel": "यात्रा", "hobby_cat_reading": "पढ़ना", "hobby_cat_cafe": "कैफ़े", "hobby_cat_photo": "फ़ोटो", "hobby_cat_cooking": "खाना बनाना", "hobby_cat_fashion": "फ़ैशन", "hobby_cat_car": "कार", "hobby_cat_pet": "पालतू",
    "purpose.hypertrophy": "मांसपेशी वृद्धि", "purpose.diet": "डाइट", "purpose.health": "स्वास्थ्य", "purpose.contest": "प्रतियोगिता", "purpose.friends": "दोस्त खोजें"
  },
  ar: {
    "nav.home": "الرئيسية", "nav.users": "أصدقاء", "nav.messages": "الرسائل", "nav.timeline": "الجدول الزمني", "nav.settings": "الإعدادات", "nav.goLive": "ابدأ",
    "common.back": "رجوع", "common.save": "حفظ", "common.edit": "تعديل", "common.delete": "حذف", "common.cancel": "إلغاء", "common.search": "بحث", "common.loading": "جارٍ التحميل…", "common.online": "متصل", "common.offline": "غير متصل", "common.send": "إرسال", "common.follow": "متابعة", "common.following": "تتابع", "common.message": "رسالة", "common.block": "حظر", "common.unblock": "إلغاء الحظر", "common.mute": "كتم", "common.unmute": "إلغاء الكتم", "common.report": "إبلاغ", "common.logout": "تسجيل الخروج", "common.all": "الكل", "common.nearby": "بالقرب", "common.trainingNow": "يتدرّب", "common.country": "الدولة", "common.hobbies": "الهوايات", "common.purpose": "الهدف", "common.bio": "نبذة", "common.displayName": "اسم المستخدم", "common.selectCountry": "اختر الدولة",
    "profile.followers": "المتابعون", "profile.following": "يتابع", "profile.posts": "المنشورات", "profile.noPosts": "لا توجد منشورات بعد", "profile.notFound": "المستخدم غير موجود", "profile.editTitle": "تعديل الملف الشخصي", "profile.editAvatar": "تغيير الصورة", "profile.noAvatar": "بدون", "profile.hobbiesMax": "الهوايات (حد أقصى 5)", "profile.purposePlaceholder": "اختر",
    "users.title": "البحث عن أصدقاء", "users.filterAll": "الكل", "users.filterNearby": "بالقرب", "users.filterTraining": "يتدرّب", "users.filterCountry": "الدولة", "users.filterHobby": "هواية", "users.filterPurpose": "الهدف", "users.noUsers": "لم يتم العثور على مستخدمين", "users.searchPlaceholder": "ابحث عن مستخدمين",
    "settings.title": "الإعدادات", "settings.editProfile": "تعديل الملف الشخصي", "settings.editHobbies": "تعديل الهوايات", "settings.editPurpose": "تعديل الهدف", "settings.notifications": "الإشعارات", "settings.language": "اللغة", "settings.darkMode": "الوضع الداكن (قريباً)", "settings.logout": "تسجيل الخروج", "settings.account": "الحساب", "settings.preferences": "التفضيلات",
    "messages.title": "الرسائل", "messages.all": "الكل", "messages.requests": "الطلبات", "messages.empty": "لا توجد رسائل. ابدأ محادثة من ملف شخصي!", "messages.emptyRequests": "لا توجد طلبات", "messages.request": "طلب رسالة", "messages.requestDesc": "أرسل لك رسالة. اقبل لبدء الدردشة.", "messages.accept": "قبول", "messages.decline": "حذف", "messages.awaiting": "بانتظار الموافقة", "messages.blocked": "لقد حظرت هذا المستخدم. لا يمكنك إرسال الرسائل.", "messages.inputPlaceholder": "اكتب رسالة…", "messages.cantSend": "لا يمكن الإرسال", "messages.acceptToStart": "اقبل لبدء الدردشة", "messages.awaitingShort": "قيد الانتظار",
    "notifications.title": "الإشعارات", "notifications.empty": "لا توجد إشعارات",
    "home.heroTitle": "درّب", "home.heroSub": "تواصل مباشر، شارك الموقع، وتنافس في الترتيب.", "home.record": "سجّل التمرين", "home.viewLive": "شاهد مباشر", "home.liveNow": "يتدرّب الآن", "home.trainingNow": "TRAINING NOW", "home.noLive": "لا أحد يتدرّب الآن. كن الأول!", "home.leaderboard": "الأعلى ترتيباً", "home.recent": "سجلات حديثة", "home.totalVolume": "إجمالي الحجم", "home.weekRecords": "هذا الأسبوع", "home.participants": "المشاركون", "home.liveCount": "مباشر", "home.globe": "كرة الأرض", "home.globeSub": "شاهد من يتدرّب حول العالم. المواقع ضبابية.", "home.trainingCount": "يتدرّب الآن", "home.noLiveMap": "لا أحد يتدرّب الآن", "home.popularPosts": "منشورات شائعة", "home.noPosts": "لا توجد منشورات", "home.nearbyMap": "خريطة محلية", "home.nearbyMapSub": "اعثر على شركاء حول العالم. أخضر = متصل، أحمر = يتدرّب الآن. انقر على الدبوس لفتح الملف.", "home.you": "أنت", "home.nearbyUser": "مستخدم قريب", "home.trainingLive": "يتدرّب الآن", "home.nearbyCount": "قريب", "home.worldView": "🌍 العالم", "home.locateMe": "الموقع الحالي", "home.satellite": "أقمار صناعية", "home.normalMap": "خريطة", "home.filter_all": "الكل", "home.filter_online": "متصل", "home.filter_training": "يتدرّب", "home.filter_following": "أتابع", "home.filter_nearby": "قريب", "home.online": "متصل", "home.offline": "غير متصل",
    "auth.selectLanguage": "اختر اللغة",     "auth.welcome": "مرحباً بك في BELTVA",
    "hobby_cat_sports": "رياضة", "hobby_cat_games": "ألعاب", "hobby_cat_music": "موسيقى", "hobby_cat_anime": "أنمي وسينما", "hobby_cat_travel": "سفر", "hobby_cat_reading": "قراءة", "hobby_cat_cafe": "مقهى", "hobby_cat_photo": "تصوير", "hobby_cat_cooking": "طبخ", "hobby_cat_fashion": "أزياء", "hobby_cat_car": "سيارات", "hobby_cat_pet": "حيوانات أليفة",
    "purpose.hypertrophy": "تضخيم العضلات", "purpose.diet": "حمية", "purpose.health": "صحة", "purpose.contest": "مسابقة", "purpose.friends": "إيجاد أصدقاء"
  },
  tr: {
    "nav.home": "Ana sayfa", "nav.users": "Arkadaşlar", "nav.messages": "Mesajlar", "nav.timeline": "Zaman çizelgesi", "nav.settings": "Ayarlar", "nav.goLive": "Başla",
    "common.back": "Geri", "common.save": "Kaydet", "common.edit": "Düzenle", "common.delete": "Sil", "common.cancel": "İptal", "common.search": "Ara", "common.loading": "Yükleniyor…", "common.online": "Çevrimiçi", "common.offline": "Çevrimdışı", "common.send": "Gönder", "common.follow": "Takip et", "common.following": "Takip ediliyor", "common.message": "Mesaj", "common.block": "Engelle", "common.unblock": "Engeli kaldır", "common.mute": "Sessize al", "common.unmute": "Sesi aç", "common.report": "Bildir", "common.logout": "Çıkış yap", "common.all": "Tümü", "common.nearby": "Yakında", "common.trainingNow": "Antrenman", "common.country": "Ülke", "common.hobbies": "Hobiler", "common.purpose": "Antrenman hedefi", "common.bio": "Hakkında", "common.displayName": "Kullanıcı adı", "common.selectCountry": "Ülke seç",
    "profile.followers": "Takipçi", "profile.following": "Takip", "profile.posts": "Gönderiler", "profile.noPosts": "Henüz gönderi yok", "profile.notFound": "Kullanıcı bulunamadı", "profile.editTitle": "Profili düzenle", "profile.editAvatar": "Fotoğraf değiştir", "profile.noAvatar": "Yok", "profile.hobbiesMax": "Hobiler (en fazla 5)", "profile.purposePlaceholder": "Seç",
    "users.title": "Arkadaş bul", "users.filterAll": "Tümü", "users.filterNearby": "Yakında", "users.filterTraining": "Antrenman", "users.filterCountry": "Ülke", "users.filterHobby": "Hobi", "users.filterPurpose": "Hedef", "users.noUsers": "Kullanıcı bulunamadı", "users.searchPlaceholder": "Kullanıcı ara",
    "settings.title": "Ayarlar", "settings.editProfile": "Profili düzenle", "settings.editHobbies": "Hobileri düzenle", "settings.editPurpose": "Hedefi düzenle", "settings.notifications": "Bildirimler", "settings.language": "Dil", "settings.darkMode": "Koyu mod (yakında)", "settings.logout": "Çıkış yap", "settings.account": "Hesap", "settings.preferences": "Tercihler",
    "messages.title": "Mesajlar", "messages.all": "Tümü", "messages.requests": "İstekler", "messages.empty": "Mesaj yok. Profilden DM başlat!", "messages.emptyRequests": "İstek yok", "messages.request": "Mesaj isteği", "messages.requestDesc": "sana mesaj gönderdi. Kabul et ve sohbet başlat.", "messages.accept": "Kabul", "messages.decline": "Sil", "messages.awaiting": "Onay bekleniyor", "messages.blocked": "Bu kullanıcıyı engelledin. Mesaj gönderemezsin.", "messages.inputPlaceholder": "Mesaj yaz…", "messages.cantSend": "Mesaj gönderilemez", "messages.acceptToStart": "Kabul et ve sohbet başlat", "messages.awaitingShort": "Beklemede",
    "notifications.title": "Bildirimler", "notifications.empty": "Bildirim yok",
    "home.heroTitle": "Antrenmana başla", "home.heroSub": "Canlı bağlan, konum paylaş, sıralamada yarış.", "home.record": "Antrenman kaydet", "home.viewLive": "Canlı izle", "home.liveNow": "Şimdi antrenman", "home.trainingNow": "TRAINING NOW", "home.noLive": "Şu an antrenman yok. İlk sen ol!", "home.leaderboard": "Üst sıralar", "home.recent": "Son kayıtlar", "home.totalVolume": "Toplam hacim", "home.weekRecords": "Bu hafta", "home.participants": "Katılımcılar", "home.liveCount": "Canlı", "home.globe": "Dünya küresi", "home.globeSub": "Dünya çapında kimin antrenman yaptığını gör. Konumlar bulanık.", "home.trainingCount": "antrenman yapıyor", "home.noLiveMap": "Şu an antrenman yok", "home.popularPosts": "Popüler gönderiler", "home.noPosts": "Henüz gönderi yok", "home.nearbyMap": "Yerel harita", "home.nearbyMapSub": "Dünya çapında antrenman partneri bul. Yeşil = çevrimiçi, kırmızı = antrenman yapıyor. Pine dokun ve profili aç.", "home.you": "Sen", "home.nearbyUser": "Yakındaki kullanıcı", "home.trainingLive": "Antrenman yapıyor", "home.nearbyCount": "yakında", "home.worldView": "🌍 Dünya", "home.locateMe": "Mevcut konum", "home.satellite": "Uydu", "home.normalMap": "Harita", "home.filter_all": "Tümü", "home.filter_online": "Çevrimiçi", "home.filter_training": "Antrenman", "home.filter_following": "Takip", "home.filter_nearby": "Yakındaki", "home.online": "Çevrimiçi", "home.offline": "Çevrimdışı",
    "auth.selectLanguage": "Dil seç", "auth.welcome": "BELTVA'ya hoş geldin",
    "hobby_cat_sports": "Spor", "hobby_cat_games": "Oyunlar", "hobby_cat_music": "Müzik", "hobby_cat_anime": "Anime ve film", "hobby_cat_travel": "Seyahat", "hobby_cat_reading": "Okuma", "hobby_cat_cafe": "Kafe", "hobby_cat_photo": "Fotoğraf", "hobby_cat_cooking": "Mutfak", "hobby_cat_fashion": "Moda", "hobby_cat_car": "Araba", "hobby_cat_pet": "Evcil hayvan",
    "purpose.hypertrophy": "Hiperrofi", "purpose.diet": "Diyet", "purpose.health": "Sağlık", "purpose.contest": "Yarışma", "purpose.friends": "Arkadaş bul"
  },
  "zh-TW": {
    "nav.home": "首頁", "nav.users": "夥伴", "nav.messages": "訊息", "nav.timeline": "動態", "nav.settings": "設定", "nav.goLive": "開始",
    "common.back": "返回", "common.save": "儲存", "common.edit": "編輯", "common.delete": "刪除", "common.cancel": "取消", "common.search": "搜尋", "common.loading": "載入中…", "common.online": "在線", "common.offline": "離線", "common.send": "發送", "common.follow": "關注", "common.following": "已關注", "common.message": "訊息", "common.block": "封鎖", "common.unblock": "取消封鎖", "common.mute": "免打擾", "common.unmute": "取消免打擾", "common.report": "檢舉", "common.logout": "登出", "common.all": "全部", "common.nearby": "附近", "common.trainingNow": "訓練中", "common.country": "國家", "common.hobbies": "興趣", "common.purpose": "訓練目標", "common.bio": "簡介", "common.displayName": "使用者名稱", "common.selectCountry": "選擇國家",
    "profile.followers": "粉絲", "profile.following": "關注", "profile.posts": "貼文", "profile.noPosts": "暫無貼文", "profile.notFound": "未找到使用者", "profile.editTitle": "編輯資料", "profile.editAvatar": "更換照片", "profile.noAvatar": "無", "profile.hobbiesMax": "興趣（最多5個）", "profile.purposePlaceholder": "請選擇",
    "users.title": "尋找夥伴", "users.filterAll": "全部", "users.filterNearby": "附近", "users.filterTraining": "訓練中", "users.filterCountry": "國家", "users.filterHobby": "興趣", "users.filterPurpose": "目標", "users.noUsers": "未找到使用者", "users.searchPlaceholder": "搜尋使用者",
    "settings.title": "設定", "settings.editProfile": "編輯資料", "settings.editHobbies": "編輯興趣", "settings.editPurpose": "編輯訓練目標", "settings.notifications": "通知設定", "settings.language": "語言", "settings.darkMode": "深色模式（即將推出）", "settings.logout": "登出", "settings.account": "帳號", "settings.preferences": "偏好",
    "messages.title": "訊息", "messages.all": "全部", "messages.requests": "請求", "messages.empty": "沒有訊息。去資料頁發起私訊吧！", "messages.emptyRequests": "沒有請求", "messages.request": "訊息請求", "messages.requestDesc": "給你發了訊息。通過後即可開始聊天。", "messages.accept": "通過", "messages.decline": "刪除", "messages.awaiting": "等待對方通過", "messages.blocked": "你已封鎖該使用者，無法發送訊息。", "messages.inputPlaceholder": "輸入訊息…", "messages.cantSend": "無法發送訊息", "messages.acceptToStart": "通過後開始聊天", "messages.awaitingShort": "待通過",
    "notifications.title": "通知", "notifications.empty": "暫無通知",
    "home.heroTitle": "開始訓練吧", "home.heroSub": "直播連線、共享位置、排行榜對決。", "home.record": "記錄訓練", "home.viewLive": "看直播", "home.liveNow": "正在訓練", "home.trainingNow": "TRAINING NOW", "home.noLive": "當前沒人訓練。成為第一個吧！", "home.leaderboard": "排行榜", "home.recent": "最新記錄", "home.totalVolume": "總訓練量", "home.weekRecords": "本週記錄", "home.participants": "參與者", "home.liveCount": "直播中", "home.globe": "世界地球", "home.globeSub": "看看世界各地正在訓練的夥伴。位置已模糊。", "home.trainingCount": "人正在訓練", "home.noLiveMap": "當前沒人訓練", "home.popularPosts": "熱門貼文", "home.noPosts": "暫無貼文", "home.nearbyMap": "本地地圖", "home.nearbyMapSub": "在全球地圖上找到訓練夥伴。綠色=在線，紅色=正在訓練。點擊圖釘查看資料。", "home.you": "你", "home.nearbyUser": "附近使用者", "home.trainingLive": "訓練中", "home.nearbyCount": "人在附近", "home.worldView": "🌍 世界", "home.locateMe": "當前位置", "home.satellite": "衛星圖", "home.normalMap": "地圖", "home.filter_all": "全部", "home.filter_online": "在線", "home.filter_training": "訓練中", "home.filter_following": "已關注", "home.filter_nearby": "附近使用者", "home.online": "在線", "home.offline": "離線",
    "auth.selectLanguage": "選擇語言", "auth.welcome": "歡迎來到 BELTVA",
    "hobby_cat_sports": "運動", "hobby_cat_games": "遊戲", "hobby_cat_music": "音樂", "hobby_cat_anime": "影視動漫", "hobby_cat_travel": "旅行", "hobby_cat_reading": "閱讀", "hobby_cat_cafe": "咖啡", "hobby_cat_photo": "攝影", "hobby_cat_cooking": "烹飪", "hobby_cat_fashion": "時尚", "hobby_cat_car": "汽車", "hobby_cat_pet": "寵物",
    "purpose.hypertrophy": "增肌", "purpose.diet": "減脂", "purpose.health": "保持健康", "purpose.contest": "參加比賽", "purpose.friends": "找夥伴"
  }
};

// Merge extra translation keys into each language
for (const _lang of Object.keys(translations)) {
  Object.assign(translations[_lang], extraTranslations[_lang] || {});
  Object.assign(translations[_lang], hobbyUITranslations[_lang] || {});
  Object.assign(translations[_lang], missingTranslations[_lang] || {});
  Object.assign(translations[_lang], voiceTranslations[_lang] || {});
  Object.assign(translations[_lang], workoutTypeTranslations[_lang] || {});
}
// Add ja identity entries for exercise names so t() doesn't fall through to en
Object.assign(translations.ja, jaExerciseIdentity.ja || {});

const RTL_LANGS = ["ar"];

const LanguageContext = createContext({ lang: "ja", setLang: () => {}, t: (k) => k });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem("beltva_lang") || localStorage.getItem("pulse_lang");
    if (saved) return saved;
    return detectDeviceLanguage();
  });

  // Sync language from user account on mount (persists across devices)
  useEffect(() => {
    base44.auth.me().then((u) => {
      if (u.language && u.language !== lang) {
        setLang(u.language);
        localStorage.setItem("beltva_lang", u.language);
      }
    }).catch(() => {});
  }, []);

  useEffect(() => {
    localStorage.setItem("beltva_lang", lang);
    if (localStorage.getItem("pulse_lang")) localStorage.removeItem("pulse_lang");
    const rtl = RTL_LANGS.includes(lang);
    document.documentElement.dir = rtl ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  // Save language to both localStorage and user account
  const setLangAndSave = (newLang) => {
    setLang(newLang);
    localStorage.setItem("beltva_lang", newLang);
    base44.auth.updateMe({ language: newLang }).catch(() => {});
  };

  const t = (key) => translations[lang]?.[key] ?? translations.ja?.[key] ?? translations.en?.[key] ?? key;
  return <LanguageContext.Provider value={{ lang, setLang: setLangAndSave, t }}>{children}</LanguageContext.Provider>;
}

export function useI18n() { return useContext(LanguageContext); }
export function useT() { return useContext(LanguageContext).t; }