import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  ja: {
    "nav.home": "ホーム", "nav.users": "ユーザー", "nav.messages": "メッセージ", "nav.timeline": "タイムライン", "nav.rankings": "ランキング", "nav.settings": "設定", "nav.goLive": "トレ開始",
    "common.back": "戻る", "common.save": "保存", "common.edit": "編集", "common.delete": "削除", "common.cancel": "キャンセル", "common.search": "検索", "common.loading": "読み込み中…", "common.online": "オンライン", "common.offline": "オフライン", "common.send": "送信", "common.follow": "フォロー", "common.following": "フォロー中", "common.message": "メッセージ", "common.block": "ブロック", "common.unblock": "ブロック解除", "common.mute": "ミュート", "common.unmute": "ミュート解除", "common.report": "通報", "common.logout": "ログアウト", "common.all": "すべて", "common.nearby": "近く", "common.trainingNow": "トレーニング中", "common.country": "国", "common.hobbies": "趣味", "common.purpose": "トレーニング目的", "common.bio": "自己紹介", "common.displayName": "ユーザー名", "common.selectCountry": "国を選択",
    "profile.followers": "フォロワー", "profile.following": "フォロー中", "profile.posts": "投稿一覧", "profile.noPosts": "まだ投稿がありません", "profile.notFound": "ユーザーが見つかりません", "profile.editTitle": "プロフィール編集", "profile.editAvatar": "画像を変更", "profile.noAvatar": "なし", "profile.hobbiesMax": "趣味（最大5つ）", "profile.purposePlaceholder": "選択してください",
    "users.title": "ユーザー", "users.filterAll": "すべて", "users.filterNearby": "近く", "users.filterTraining": "トレ中", "users.filterCountry": "国", "users.filterHobby": "趣味", "users.filterPurpose": "目的", "users.noUsers": "ユーザーが見つかりません", "users.searchPlaceholder": "ユーザーを検索",
    "settings.title": "設定", "settings.editProfile": "プロフィール編集", "settings.editHobbies": "趣味を編集", "settings.editPurpose": "トレーニング目的を編集", "settings.notifications": "通知設定", "settings.language": "言語", "settings.darkMode": "ダークモード（今後対応）", "settings.logout": "ログアウト", "settings.account": "アカウント", "settings.preferences": "設定",
    "messages.title": "メッセージ", "messages.all": "すべて", "messages.requests": "リクエスト", "messages.empty": "メッセージはありません。プロフィールからDMを始めよう！", "messages.emptyRequests": "リクエストはありません", "messages.request": "メッセージリクエスト", "messages.requestDesc": "さんからのメッセージです。承認するとチャットを始められます。", "messages.accept": "承認", "messages.decline": "削除", "messages.awaiting": "相手の承認待ちです", "messages.blocked": "このユーザーをブロックしているため、メッセージを送れません。", "messages.inputPlaceholder": "メッセージを入力…", "messages.cantSend": "メッセージを送れません", "messages.acceptToStart": "承認してチャットを始めよう", "messages.awaitingShort": "承認待ち",
    "notifications.title": "通知", "notifications.empty": "通知はありません",
    "home.heroTitle": "トレーニングを始めよう", "home.heroSub": "ライブ配信で仲間と繋がり、位置情報を共有し、ランキング対決で本気を出す。", "home.record": "トレーニング記録", "home.viewLive": "ライブを見る", "home.liveNow": "いまトレーニング中", "home.trainingNow": "TRAINING NOW", "home.noLive": "いまトレーニング中の仲間はいません。最初にトレーニングを始めよう！", "home.leaderboard": "トップランカー", "home.recent": "みんなの記録", "home.totalVolume": "総ボリューム", "home.weekRecords": "今週の記録", "home.participants": "参加者", "home.liveCount": "配信中", "home.globe": "ワールドグローブ", "home.globeSub": "世界中でいま筋トレしている仲間が光る。位置は近隣にぼかして表示しています。", "home.trainingCount": "人 トレーニング中", "home.noLiveMap": "いまトレーニング中の仲間はいません",
    "auth.selectLanguage": "言語を選択", "auth.welcome": "PULSEへようこそ",
    "hobby_cat_sports": "スポーツ", "hobby_cat_games": "ゲーム", "hobby_cat_music": "音楽", "hobby_cat_anime": "映画・アニメ", "hobby_cat_travel": "旅行", "hobby_cat_reading": "読書", "hobby_cat_cafe": "カフェ", "hobby_cat_photo": "写真", "hobby_cat_cooking": "料理", "hobby_cat_fashion": "ファッション", "hobby_cat_car": "車", "hobby_cat_pet": "ペット",
    "purpose.hypertrophy": "筋肥大", "purpose.diet": "ダイエット", "purpose.health": "健康維持", "purpose.contest": "大会出場", "purpose.friends": "仲間募集"
  },
  en: {
    "nav.home": "Home", "nav.users": "Users", "nav.messages": "Messages", "nav.timeline": "Timeline", "nav.rankings": "Rankings", "nav.settings": "Settings", "nav.goLive": "Start",
    "common.back": "Back", "common.save": "Save", "common.edit": "Edit", "common.delete": "Delete", "common.cancel": "Cancel", "common.search": "Search", "common.loading": "Loading…", "common.online": "Online", "common.offline": "Offline", "common.send": "Send", "common.follow": "Follow", "common.following": "Following", "common.message": "Message", "common.block": "Block", "common.unblock": "Unblock", "common.mute": "Mute", "common.unmute": "Unmute", "common.report": "Report", "common.logout": "Log out", "common.all": "All", "common.nearby": "Nearby", "common.trainingNow": "Training", "common.country": "Country", "common.hobbies": "Hobbies", "common.purpose": "Training goal", "common.bio": "Bio", "common.displayName": "Username", "common.selectCountry": "Select country",
    "profile.followers": "Followers", "profile.following": "Following", "profile.posts": "Posts", "profile.noPosts": "No posts yet", "profile.notFound": "User not found", "profile.editTitle": "Edit profile", "profile.editAvatar": "Change photo", "profile.noAvatar": "None", "profile.hobbiesMax": "Hobbies (up to 5)", "profile.purposePlaceholder": "Select",
    "users.title": "Users", "users.filterAll": "All", "users.filterNearby": "Nearby", "users.filterTraining": "Training", "users.filterCountry": "Country", "users.filterHobby": "Hobby", "users.filterPurpose": "Goal", "users.noUsers": "No users found", "users.searchPlaceholder": "Search users",
    "settings.title": "Settings", "settings.editProfile": "Edit profile", "settings.editHobbies": "Edit hobbies", "settings.editPurpose": "Edit training goal", "settings.notifications": "Notifications", "settings.language": "Language", "settings.darkMode": "Dark mode (coming soon)", "settings.logout": "Log out", "settings.account": "Account", "settings.preferences": "Preferences",
    "messages.title": "Messages", "messages.all": "All", "messages.requests": "Requests", "messages.empty": "No messages. Start a DM from a profile!", "messages.emptyRequests": "No requests", "messages.request": "Message request", "messages.requestDesc": "sent you a message. Accept to start chatting.", "messages.accept": "Accept", "messages.decline": "Delete", "messages.awaiting": "Waiting for approval", "messages.blocked": "You blocked this user. You can't send messages.", "messages.inputPlaceholder": "Type a message…", "messages.cantSend": "Can't send messages", "messages.acceptToStart": "Accept to start chatting", "messages.awaitingShort": "Pending",
    "notifications.title": "Notifications", "notifications.empty": "No notifications",
    "home.heroTitle": "Let's train", "home.heroSub": "Connect live, share location, and compete on the leaderboard.", "home.record": "Log workout", "home.viewLive": "Watch live", "home.liveNow": "Training now", "home.trainingNow": "TRAINING NOW", "home.noLive": "No one training right now. Be the first!", "home.leaderboard": "Top rankers", "home.recent": "Recent records", "home.totalVolume": "Total volume", "home.weekRecords": "This week", "home.participants": "Participants", "home.liveCount": "Live", "home.globe": "World globe", "home.globeSub": "See who's training worldwide. Locations are blurred.", "home.trainingCount": "training now", "home.noLiveMap": "No one training right now",
    "auth.selectLanguage": "Select language", "auth.welcome": "Welcome to PULSE",
    "hobby_cat_sports": "Sports", "hobby_cat_games": "Games", "hobby_cat_music": "Music", "hobby_cat_anime": "Anime & Film", "hobby_cat_travel": "Travel", "hobby_cat_reading": "Reading", "hobby_cat_cafe": "Cafe", "hobby_cat_photo": "Photo", "hobby_cat_cooking": "Cooking", "hobby_cat_fashion": "Fashion", "hobby_cat_car": "Car", "hobby_cat_pet": "Pet",
    "purpose.hypertrophy": "Hypertrophy", "purpose.diet": "Diet", "purpose.health": "Health", "purpose.contest": "Contest", "purpose.friends": "Find friends"
  },
  zh: {
    "nav.home": "首页", "nav.users": "用户", "nav.messages": "消息", "nav.timeline": "动态", "nav.rankings": "排行榜", "nav.settings": "设置", "nav.goLive": "开始",
    "common.back": "返回", "common.save": "保存", "common.edit": "编辑", "common.delete": "删除", "common.cancel": "取消", "common.search": "搜索", "common.loading": "加载中…", "common.online": "在线", "common.offline": "离线", "common.send": "发送", "common.follow": "关注", "common.following": "已关注", "common.message": "消息", "common.block": "拉黑", "common.unblock": "取消拉黑", "common.mute": "免打扰", "common.unmute": "取消免打扰", "common.report": "举报", "common.logout": "退出登录", "common.all": "全部", "common.nearby": "附近", "common.trainingNow": "训练中", "common.country": "国家", "common.hobbies": "兴趣", "common.purpose": "训练目标", "common.bio": "简介", "common.displayName": "用户名", "common.selectCountry": "选择国家",
    "profile.followers": "粉丝", "profile.following": "关注", "profile.posts": "帖子", "profile.noPosts": "暂无帖子", "profile.notFound": "未找到用户", "profile.editTitle": "编辑资料", "profile.editAvatar": "更换照片", "profile.noAvatar": "无", "profile.hobbiesMax": "兴趣（最多5个）", "profile.purposePlaceholder": "请选择",
    "users.title": "用户", "users.filterAll": "全部", "users.filterNearby": "附近", "users.filterTraining": "训练中", "users.filterCountry": "国家", "users.filterHobby": "兴趣", "users.filterPurpose": "目标", "users.noUsers": "未找到用户", "users.searchPlaceholder": "搜索用户",
    "settings.title": "设置", "settings.editProfile": "编辑资料", "settings.editHobbies": "编辑兴趣", "settings.editPurpose": "编辑训练目标", "settings.notifications": "通知设置", "settings.language": "语言", "settings.darkMode": "深色模式（即将推出）", "settings.logout": "退出登录", "settings.account": "账号", "settings.preferences": "偏好",
    "messages.title": "消息", "messages.all": "全部", "messages.requests": "请求", "messages.empty": "没有消息。去资料页发起私信吧！", "messages.emptyRequests": "没有请求", "messages.request": "消息请求", "messages.requestDesc": "给你发了消息。通过后即可开始聊天。", "messages.accept": "通过", "messages.decline": "删除", "messages.awaiting": "等待对方通过", "messages.blocked": "你已拉黑该用户，无法发送消息。", "messages.inputPlaceholder": "输入消息…", "messages.cantSend": "无法发送消息", "messages.acceptToStart": "通过后开始聊天", "messages.awaitingShort": "待通过",
    "notifications.title": "通知", "notifications.empty": "暂无通知",
    "home.heroTitle": "开始训练吧", "home.heroSub": "直播连线、共享位置、排行榜对决。", "home.record": "记录训练", "home.viewLive": "看直播", "home.liveNow": "正在训练", "home.trainingNow": "TRAINING NOW", "home.noLive": "当前没人训练。成为第一个吧！", "home.leaderboard": "排行榜", "home.recent": "最新记录", "home.totalVolume": "总训练量", "home.weekRecords": "本周记录", "home.participants": "参与者", "home.liveCount": "直播中", "home.globe": "世界地球", "home.globeSub": "看看世界各地正在训练的伙伴。位置已模糊。", "home.trainingCount": "人正在训练", "home.noLiveMap": "当前没人训练",
    "auth.selectLanguage": "选择语言", "auth.welcome": "欢迎来到 PULSE",
    "hobby_cat_sports": "运动", "hobby_cat_games": "游戏", "hobby_cat_music": "音乐", "hobby_cat_anime": "影视动漫", "hobby_cat_travel": "旅行", "hobby_cat_reading": "阅读", "hobby_cat_cafe": "咖啡", "hobby_cat_photo": "摄影", "hobby_cat_cooking": "烹饪", "hobby_cat_fashion": "时尚", "hobby_cat_car": "汽车", "hobby_cat_pet": "宠物",
    "purpose.hypertrophy": "增肌", "purpose.diet": "减脂", "purpose.health": "保持健康", "purpose.contest": "参加比赛", "purpose.friends": "找伙伴"
  },
  ko: {
    "nav.home": "홈", "nav.users": "유저", "nav.messages": "메시지", "nav.timeline": "타임라인", "nav.rankings": "랭킹", "nav.settings": "설정", "nav.goLive": "시작",
    "common.back": "뒤로", "common.save": "저장", "common.edit": "편집", "common.delete": "삭제", "common.cancel": "취소", "common.search": "검색", "common.loading": "로딩 중…", "common.online": "온라인", "common.offline": "오프라인", "common.send": "전송", "common.follow": "팔로우", "common.following": "팔로잉", "common.message": "메시지", "common.block": "차단", "common.unblock": "차단 해제", "common.mute": "알림 끄기", "common.unmute": "알림 켜기", "common.report": "신고", "common.logout": "로그아웃", "common.all": "전체", "common.nearby": "근처", "common.trainingNow": "운동 중", "common.country": "국가", "common.hobbies": "취미", "common.purpose": "운동 목표", "common.bio": "소개", "common.displayName": "유저명", "common.selectCountry": "국가 선택",
    "profile.followers": "팔로워", "profile.following": "팔로잉", "profile.posts": "게시물", "profile.noPosts": "게시물이 없습니다", "profile.notFound": "유저를 찾을 수 없습니다", "profile.editTitle": "프로필 편집", "profile.editAvatar": "사진 변경", "profile.noAvatar": "없음", "profile.hobbiesMax": "취미 (최대 5개)", "profile.purposePlaceholder": "선택",
    "users.title": "유저", "users.filterAll": "전체", "users.filterNearby": "근처", "users.filterTraining": "운동 중", "users.filterCountry": "국가", "users.filterHobby": "취미", "users.filterPurpose": "목표", "users.noUsers": "유저가 없습니다", "users.searchPlaceholder": "유저 검색",
    "settings.title": "설정", "settings.editProfile": "프로필 편집", "settings.editHobbies": "취미 편집", "settings.editPurpose": "운동 목표 편집", "settings.notifications": "알림 설정", "settings.language": "언어", "settings.darkMode": "다크 모드 (예정)", "settings.logout": "로그아웃", "settings.account": "계정", "settings.preferences": "환경설정",
    "messages.title": "메시지", "messages.all": "전체", "messages.requests": "요청", "messages.empty": "메시지가 없습니다. 프로필에서 DM을 시작하세요!", "messages.emptyRequests": "요청이 없습니다", "messages.request": "메시지 요청", "messages.requestDesc": "님이 메시지를 보냈습니다. 승인하면 채팅을 시작할 수 있습니다.", "messages.accept": "승인", "messages.decline": "삭제", "messages.awaiting": "상대 승인 대기 중", "messages.blocked": "이 유저를 차단하여 메시지를 보낼 수 없습니다.", "messages.inputPlaceholder": "메시지 입력…", "messages.cantSend": "메시지를 보낼 수 없습니다", "messages.acceptToStart": "승인하여 채팅 시작", "messages.awaitingShort": "대기 중",
    "notifications.title": "알림", "notifications.empty": "알림이 없습니다",
    "home.heroTitle": "운동을 시작해요", "home.heroSub": "라이브로 친구와 연결하고 위치를 공유하며 랭킹 대결.", "home.record": "운동 기록", "home.viewLive": "라이브 보기", "home.liveNow": "지금 운동 중", "home.trainingNow": "TRAINING NOW", "home.noLive": "지금 운동 중인 친구가 없습니다. 먼저 시작해 보세요!", "home.leaderboard": "탑 랭커", "home.recent": "최근 기록", "home.totalVolume": "총 볼륨", "home.weekRecords": "이번 주 기록", "home.participants": "참가자", "home.liveCount": "라이브", "home.globe": "월드 글로브", "home.globeSub": "전 세계에서 운동 중인 친구들이 빛납니다. 위치는 흐려져 표시됩니다.", "home.trainingCount": "명 운동 중", "home.noLiveMap": "지금 운동 중인 친구가 없습니다",
    "auth.selectLanguage": "언어 선택", "auth.welcome": "PULSE에 오신 것을 환영합니다",
    "hobby_cat_sports": "스포츠", "hobby_cat_games": "게임", "hobby_cat_music": "음악", "hobby_cat_anime": "영화/애니", "hobby_cat_travel": "여행", "hobby_cat_reading": "독서", "hobby_cat_cafe": "카페", "hobby_cat_photo": "사진", "hobby_cat_cooking": "요리", "hobby_cat_fashion": "패션", "hobby_cat_car": "자동차", "hobby_cat_pet": "반려동물",
    "purpose.hypertrophy": "근비대", "purpose.diet": "다이어트", "purpose.health": "건강 유지", "purpose.contest": "대회 출전", "purpose.friends": "친구 모집"
  }
};

const LanguageContext = createContext({ lang: "ja", setLang: () => {}, t: (k) => k });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("pulse_lang") || "ja");
  useEffect(() => { localStorage.setItem("pulse_lang", lang); }, [lang]);
  const t = (key) => (translations[lang] && translations[lang][key]) || translations.ja[key] || key;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useI18n() { return useContext(LanguageContext); }
export function useT() { return useContext(LanguageContext).t; }